#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Opcode {
    Aaa,
    Aad,
    Aam,
    Aas,
    Adc,
    Add,
    And,
    Call,
    Cbw,
    Clc,
    Cld,
    Cli,
    Cmc,
    Cmp,
    Cmpsb,
    Cmpsw,
    Cwd,
    Daa,
    Das,
    Dec,
    Div,
    Hlt,
    Idiv,
    Imul,
    In,
    Inc,
    Int,
    Into,
    Iret,
    Ja,
    Jb,
    Jbe,
    Jcxz,
    Jg,
    Jge,
    Jl,
    Jle,
    Jmp,
    Jno,
    Jnb,
    Jns,
    Jnz,
    Jo,
    Jpe,
    Jpo,
    Js,
    Jz,
    Lahf,
    Lds,
    Lea,
    Les,
    Lock,
    Loop,
    Loopnz,
    Loopz,
    Lodsb,
    Lodsw,
    Mov,
    Movsb,
    Movsw,
    Mul,
    Neg,
    Nop,
    Not,
    Or,
    Out,
    Pop,
    Popf,
    Push,
    Pushf,
    Rcl,
    Rcr,
    Ret,
    Retf,
    Rol,
    Ror,
    Sahf,
    Sal,
    Sar,
    Sbb,
    Scasb,
    Scasw,
    Shl,
    Shr,
    Std,
    Sti,
    Stc,
    Stosb,
    Stosw,
    Sub,
    Test,
    Wait,
    Xchg,
    Xlat,
    Xor,
    ChaniCallback,
    Unknown,
}

impl Opcode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Opcode::Aaa => "aaa",
            Opcode::Aad => "aad",
            Opcode::Aam => "aam",
            Opcode::Aas => "aas",
            Opcode::Adc => "adc",
            Opcode::Add => "add",
            Opcode::And => "and",
            Opcode::Call => "call",
            Opcode::Cbw => "cbw",
            Opcode::Clc => "clc",
            Opcode::Cld => "cld",
            Opcode::Cli => "cli",
            Opcode::Cmc => "cmc",
            Opcode::Cmp => "cmp",
            Opcode::Cmpsb => "cmpsb",
            Opcode::Cmpsw => "cmpsw",
            Opcode::Cwd => "cwd",
            Opcode::Daa => "daa",
            Opcode::Das => "das",
            Opcode::Dec => "dec",
            Opcode::Div => "div",
            Opcode::Hlt => "hlt",
            Opcode::Idiv => "idiv",
            Opcode::Imul => "imul",
            Opcode::In => "in",
            Opcode::Inc => "inc",
            Opcode::Int => "int",
            Opcode::Into => "into",
            Opcode::Iret => "iret",
            Opcode::Ja => "ja",
            Opcode::Jb => "jb",
            Opcode::Jbe => "jbe",
            Opcode::Jcxz => "jcxz",
            Opcode::Jg => "jg",
            Opcode::Jge => "jge",
            Opcode::Jl => "jl",
            Opcode::Jle => "jle",
            Opcode::Jmp => "jmp",
            Opcode::Jno => "jno",
            Opcode::Jnb => "jnb",
            Opcode::Jns => "jns",
            Opcode::Jnz => "jnz",
            Opcode::Jo => "jo",
            Opcode::Jpe => "jpe",
            Opcode::Jpo => "jpo",
            Opcode::Js => "js",
            Opcode::Jz => "jz",
            Opcode::Lahf => "lahf",
            Opcode::Lds => "lds",
            Opcode::Lea => "lea",
            Opcode::Les => "les",
            Opcode::Lock => "lock",
            Opcode::Loop => "loop",
            Opcode::Loopnz => "loopnz",
            Opcode::Loopz => "loopz",
            Opcode::Lodsb => "lodsb",
            Opcode::Lodsw => "lodsw",
            Opcode::Mov => "mov",
            Opcode::Movsb => "movsb",
            Opcode::Movsw => "movsw",
            Opcode::Mul => "mul",
            Opcode::Neg => "neg",
            Opcode::Nop => "nop",
            Opcode::Not => "not",
            Opcode::Or => "or",
            Opcode::Out => "out",
            Opcode::Pop => "pop",
            Opcode::Popf => "popf",
            Opcode::Push => "push",
            Opcode::Pushf => "pushf",
            Opcode::Rcl => "rcl",
            Opcode::Rcr => "rcr",
            Opcode::Ret => "ret",
            Opcode::Retf => "retf",
            Opcode::Rol => "rol",
            Opcode::Ror => "ror",
            Opcode::Sahf => "sahf",
            Opcode::Sal => "sal",
            Opcode::Sar => "sar",
            Opcode::Sbb => "sbb",
            Opcode::Scasb => "scasb",
            Opcode::Scasw => "scasw",
            Opcode::Shl => "shl",
            Opcode::Shr => "shr",
            Opcode::Std => "std",
            Opcode::Sti => "sti",
            Opcode::Stc => "stc",
            Opcode::Stosb => "stosb",
            Opcode::Stosw => "stosw",
            Opcode::Sub => "sub",
            Opcode::Test => "test",
            Opcode::Wait => "wait",
            Opcode::Xchg => "xchg",
            Opcode::Xlat => "xlat",
            Opcode::Xor => "xor",
            Opcode::ChaniCallback => "chani-callback",
            Opcode::Unknown => "",
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ArgType {
    Inherit,
    None,
    Const1,
    Const3,
    AL,
    CL,
    DL,
    BL,
    AH,
    CH,
    DH,
    BH,
    AX,
    CX,
    DX,
    BX,
    SP,
    BP,
    SI,
    DI,
    ES,
    CS,
    SS,
    DS,
    Reg8,
    Reg16,
    SReg,
    Imm8,
    Imm16,
    Rel8,
    Rel16,
    IMem8,
    IMem16,
    IMem32,
    // Mem8,
    Mem16,
    Mem32,
    RM8,
    RM16,
}

impl ArgType {
    pub fn needs_width_specifier(&self) -> bool {
        matches!(self, Self::None | Self::Imm8 | Self::Imm16)
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ArgDir {
    None,
    RO = 1, // Read only
    RW,     // Read/write
    WO,     // Write only
    Inherit,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Flag {
    None,
    ModRM,
    Group,
}

#[derive(Clone, Debug)]
pub struct Instruction {
    pub opcode: Opcode,
    pub flag: Flag,
    pub arg_type: [ArgType; 2],
    pub arg_dir: [ArgDir; 2],
}

impl Instruction {
    pub fn needs_modrm(&self) -> bool {
        matches!(self.flag, Flag::ModRM | Flag::Group)
    }
}

macro_rules! group {
    () => {
        Some(Instruction {
            opcode: Opcode::Unknown,
            flag: Flag::Group,
            arg_type: [ArgType::None, ArgType::None],
            arg_dir: [ArgDir::None, ArgDir::None],
        })
    };
    ($arg1ty:tt, $arg1dir:tt) => {
        Some(Instruction {
            opcode: Opcode::Unknown,
            flag: Flag::Group,
            arg_type: [ArgType::$arg1ty, ArgType::None],
            arg_dir: [ArgDir::$arg1dir, ArgDir::None],
        })
    };
    ($arg1ty:tt, $arg2ty:tt, $arg1dir:tt, $arg2dir:tt) => {
        Some(Instruction {
            opcode: Opcode::Unknown,
            flag: Flag::Group,
            arg_type: [ArgType::$arg1ty, ArgType::$arg2ty],
            arg_dir: [ArgDir::$arg1dir, ArgDir::$arg2dir],
        })
    };
}

macro_rules! opcode {
    ($op:ident) => {
        Some(Instruction {
            opcode: Opcode::$op,
            flag: Flag::None,
            arg_type: [ArgType::None, ArgType::None],
            arg_dir: [ArgDir::None, ArgDir::None],
        })
    };
    ($op:ident, $flag:tt, $arg1ty:tt, $arg1dir:tt) => {
        Some(Instruction {
            opcode: Opcode::$op,
            flag: Flag::$flag,
            arg_type: [ArgType::$arg1ty, ArgType::None],
            arg_dir: [ArgDir::$arg1dir, ArgDir::None],
        })
    };
    ($op:ident, $flag:tt, $arg1ty:tt, $arg2ty:tt, $arg1dir:tt, $arg2dir:tt) => {
        Some(Instruction {
            opcode: Opcode::$op,
            flag: Flag::$flag,
            arg_type: [ArgType::$arg1ty, ArgType::$arg2ty],
            arg_dir: [ArgDir::$arg1dir, ArgDir::$arg2dir],
        })
    };
}

#[rustfmt::skip]
pub static OPCODE_TABLE: [Option<Instruction>; 256] = [
    /* 00 */ opcode!(Add,  ModRM, RM8, Reg8, RW, RO),
    /* 01 */ opcode!(Add,  ModRM, RM16, Reg16, RW, RO),
    /* 02 */ opcode!(Add,  ModRM, Reg8, RM8, RW, RO),
    /* 03 */ opcode!(Add,  ModRM, Reg16, RM16, RW, RO),
    /* 04 */ opcode!(Add,  None, AL, Imm8, RW, RO),
    /* 05 */ opcode!(Add,  None, AX, Imm16, RW, RO),
    /* 06 */ opcode!(Push, None, ES, RO),
    /* 07 */ opcode!(Pop,  None, ES, WO),
    /* 08 */ opcode!(Or,   ModRM, RM8, Reg8, RW, RO),
    /* 09 */ opcode!(Or,   ModRM, RM16, Reg16, RW, RO),
    /* 0a */ opcode!(Or,   ModRM, Reg8, RM8, RW, RO),
    /* 0b */ opcode!(Or,   ModRM, Reg16, RM16, RW, RO),
    /* 0c */ opcode!(Or,   None, AL, Imm8, RW, RO),
    /* 0d */ opcode!(Or,   None, AX, Imm16, RW, RO),
    /* 0e */ opcode!(Push, None, CS, RO),
    /* 0f */ opcode!(Pop,  None, CS, WO),
    /* 10 */ opcode!(Adc,  ModRM, RM8, Reg8, RW, RO),
    /* 11 */ opcode!(Adc,  ModRM, RM16, Reg16, RW, RO),
    /* 12 */ opcode!(Adc,  ModRM, Reg8, RM8, RW, RO),
    /* 13 */ opcode!(Adc,  ModRM, Reg16, RM16, RW, RO),
    /* 14 */ opcode!(Adc,  None, AL, Imm8, RW, RO),
    /* 15 */ opcode!(Adc,  None, AX, Imm16, RW, RO),
    /* 16 */ opcode!(Push, None, SS, RO),
    /* 17 */ opcode!(Pop,  None, SS, RO),
    /* 18 */ opcode!(Sbb,  ModRM, RM8, Reg8, RW, RO),
    /* 19 */ opcode!(Sbb,  ModRM, RM16, Reg16, RW, RO),
    /* 1a */ opcode!(Sbb,  ModRM, Reg8, RM8, RW, RO),
    /* 1b */ opcode!(Sbb,  ModRM, Reg16, RM16, RW, RO),
    /* 1c */ opcode!(Sbb,  None, AL, Imm8, RW, RO),
    /* 1d */ opcode!(Sbb,  None, AX, Imm16, RW, RO),
    /* 1e */ opcode!(Push, None, DS, RO),
    /* 1f */ opcode!(Pop,  None, DS, WO),
    /* 20 */ opcode!(And,  ModRM, RM8, Reg8, RW, RO),
    /* 21 */ opcode!(And,  ModRM, RM16, Reg16, RW, RO),
    /* 22 */ opcode!(And,  ModRM, Reg8, RM8, RW, RO),
    /* 23 */ opcode!(And,  ModRM, Reg16, RM16, RW, RO),
    /* 24 */ opcode!(And,  None, AL, Imm8, RW, RO),
    /* 25 */ opcode!(And,  None, AX, Imm16, RW, RO),
    /* 26 */ None,
    /* 27 */ opcode!(Daa),
    /* 28 */ opcode!(Sub,  ModRM, RM8, Reg8, RW, RO),
    /* 29 */ opcode!(Sub,  ModRM, RM16, Reg16, RW, RO),
    /* 2a */ opcode!(Sub,  ModRM, Reg8, RM8, RW, RO),
    /* 2b */ opcode!(Sub,  ModRM, Reg16, RM16, RW, RO),
    /* 2c */ opcode!(Sub,  None, AL, Imm8, RW, RO),
    /* 2d */ opcode!(Sub,  None, AX, Imm16, RW, RO),
    /* 2e */ None,
    /* 2f */ opcode!(Das),
    /* 30 */ opcode!(Xor,  ModRM, RM8, Reg8, RW, RO),
    /* 31 */ opcode!(Xor,  ModRM, RM16, Reg16, RW, RO),
    /* 32 */ opcode!(Xor,  ModRM, Reg8, RM8, RW, RO),
    /* 33 */ opcode!(Xor,  ModRM, Reg16, RM16, RW, RO),
    /* 34 */ opcode!(Xor,  None, AL, Imm8, RW, RO),
    /* 35 */ opcode!(Xor,  None, AX, Imm16, RW, RO),
    /* 36 */ None,
    /* 37 */ opcode!(Aaa),
    /* 38 */ opcode!(Cmp,  ModRM, RM8, Reg8, RO, RO),
    /* 39 */ opcode!(Cmp,  ModRM, RM16, Reg16, RO, RO),
    /* 3a */ opcode!(Cmp,  ModRM, Reg8, RM8, RO, RO),
    /* 3b */ opcode!(Cmp,  ModRM, Reg16, RM16, RO, RO),
    /* 3c */ opcode!(Cmp,  None, AL, Imm8, RO, RO),
    /* 3d */ opcode!(Cmp,  None, AX, Imm16, RO, RO),
    /* 3e */ None,
    /* 3f */ opcode!(Aas),
    /* 40 */ opcode!(Inc,  None, AX, RW),
    /* 41 */ opcode!(Inc,  None, CX, RW),
    /* 42 */ opcode!(Inc,  None, DX, RW),
    /* 43 */ opcode!(Inc,  None, BX, RW),
    /* 44 */ opcode!(Inc,  None, SP, RW),
    /* 45 */ opcode!(Inc,  None, BP, RW),
    /* 46 */ opcode!(Inc,  None, SI, RW),
    /* 47 */ opcode!(Inc,  None, DI, RW),
    /* 48 */ opcode!(Dec,  None, AX, RW),
    /* 49 */ opcode!(Dec,  None, CX, RW),
    /* 4a */ opcode!(Dec,  None, DX, RW),
    /* 4b */ opcode!(Dec,  None, BX, RW),
    /* 4c */ opcode!(Dec,  None, SP, RW),
    /* 4d */ opcode!(Dec,  None, BP, RW),
    /* 4e */ opcode!(Dec,  None, SI, RW),
    /* 4f */ opcode!(Dec,  None, DI, RW),
    /* 50 */ opcode!(Push, None, AX, RO),
    /* 51 */ opcode!(Push, None, CX, RO),
    /* 52 */ opcode!(Push, None, DX, RO),
    /* 53 */ opcode!(Push, None, BX, RO),
    /* 54 */ opcode!(Push, None, SP, RO),
    /* 55 */ opcode!(Push, None, BP, RO),
    /* 56 */ opcode!(Push, None, SI, RO),
    /* 57 */ opcode!(Push, None, DI, RO),
    /* 58 */ opcode!(Pop,  None, AX, WO),
    /* 59 */ opcode!(Pop,  None, CX, WO),
    /* 5a */ opcode!(Pop,  None, DX, WO),
    /* 5b */ opcode!(Pop,  None, BX, WO),
    /* 5c */ opcode!(Pop,  None, SP, WO),
    /* 5d */ opcode!(Pop,  None, BP, WO),
    /* 5e */ opcode!(Pop,  None, SI, WO),
    /* 5f */ opcode!(Pop,  None, DI, WO),
    /* 60 */ None,
    /* 61 */ None,
    /* 62 */ None,
    /* 63 */ None,
    /* 64 */ None,
    /* 65 */ None,
    /* 66 */ None,
    /* 67 */ None,
    /* 68 */ None,
    /* 69 */ None,
    /* 6a */ None,
    /* 6b */ None,
    /* 6c */ None,
    /* 6d */ None,
    /* 6e */ None,
    /* 6f */ None,
    /* 70 */ opcode!(Jo,   None, Rel8, RO),
    /* 71 */ opcode!(Jno,  None, Rel8, RO),
    /* 72 */ opcode!(Jb,   None, Rel8, RO),
    /* 73 */ opcode!(Jnb,  None, Rel8, RO),
    /* 74 */ opcode!(Jz,   None, Rel8, RO),
    /* 75 */ opcode!(Jnz,  None, Rel8, RO),
    /* 76 */ opcode!(Jbe,  None, Rel8, RO),
    /* 77 */ opcode!(Ja,   None, Rel8, RO),
    /* 78 */ opcode!(Js,   None, Rel8, RO),
    /* 79 */ opcode!(Jns,  None, Rel8, RO),
    /* 7a */ opcode!(Jpe,  None, Rel8, RO),
    /* 7b */ opcode!(Jpo,  None, Rel8, RO),
    /* 7c */ opcode!(Jl,   None, Rel8, RO),
    /* 7d */ opcode!(Jge,  None, Rel8, RO),
    /* 7e */ opcode!(Jle,  None, Rel8, RO),
    /* 7f */ opcode!(Jg,   None, Rel8, RO),
    /* 80 */ group!(         RM8, Imm8, RW, RO),
    /* 81 */ group!(         RM16, Imm16, RW, RO),
    /* 82 */ group!(         RM8, Imm8, RW, RO),
    /* 83 */ group!(         RM16, Imm8, RW, RO),
    /* 84 */ opcode!(Test, ModRM, Reg8, RM8, RO, RO),
    /* 85 */ opcode!(Test, ModRM, Reg16, RM16, RO, RO),
    /* 86 */ opcode!(Xchg, ModRM, Reg8, RM8, RW, RW),
    /* 87 */ opcode!(Xchg, ModRM, Reg16, RM16, RW, RW),
    /* 88 */ opcode!(Mov,  ModRM, RM8, Reg8, WO, RO),
    /* 89 */ opcode!(Mov,  ModRM, RM16, Reg16, WO, RO),
    /* 8a */ opcode!(Mov,  ModRM, Reg8, RM8, WO, RO),
    /* 8b */ opcode!(Mov,  ModRM, Reg16, RM16, WO, RO),
    /* 8c */ opcode!(Mov,  ModRM, RM16, SReg, WO, RO),
    /* 8d */ opcode!(Lea,  ModRM, Reg16, Mem16, RO, RO),
    /* 8e */ opcode!(Mov,  ModRM, SReg, RM16, WO, RO),
    /* 8f */ opcode!(Pop,  ModRM, RM16, WO),
    /* 90 */ opcode!(Nop),
    /* 91 */ opcode!(Xchg, None, CX, AX, RW, RW),
    /* 92 */ opcode!(Xchg, None, DX, AX, RW, RW),
    /* 93 */ opcode!(Xchg, None, BX, AX, RW, RW),
    /* 94 */ opcode!(Xchg, None, SP, AX, RW, RW),
    /* 95 */ opcode!(Xchg, None, BP, AX, RW, RW),
    /* 96 */ opcode!(Xchg, None, SI, AX, RW, RW),
    /* 97 */ opcode!(Xchg, None, DI, AX, RW, RW),
    /* 98 */ opcode!(Cbw),
    /* 99 */ opcode!(Cwd),
    /* 9a */ opcode!(Call, None, IMem32, RO),
    /* 9b */ opcode!(Wait),
    /* 9c */ opcode!(Pushf),
    /* 9d */ opcode!(Popf),
    /* 9e */ opcode!(Sahf),
    /* 9f */ opcode!(Lahf),
    /* a0 */ opcode!(Mov,  None, AL, IMem8, WO, RO),
    /* a1 */ opcode!(Mov,  None, AX, IMem16, WO, RO),
    /* a2 */ opcode!(Mov,  None, IMem8, AL, WO, RO),
    /* a3 */ opcode!(Mov,  None, IMem16, AX, WO, RO),
    /* a4 */ opcode!(Movsb),
    /* a5 */ opcode!(Movsw),
    /* a6 */ opcode!(Cmpsb),
    /* a7 */ opcode!(Cmpsw),
    /* a8 */ opcode!(Test, None, AL, Imm8, RO, RO),
    /* a9 */ opcode!(Test, None, AX, Imm16, RO, RO),
    /* aa */ opcode!(Stosb),
    /* ab */ opcode!(Stosw),
    /* ac */ opcode!(Lodsb),
    /* ad */ opcode!(Lodsw),
    /* ae */ opcode!(Scasb),
    /* af */ opcode!(Scasw),
    /* b0 */ opcode!(Mov,  None, AL, Imm8, WO, RO),
    /* b1 */ opcode!(Mov,  None, CL, Imm8, WO, RO),
    /* b2 */ opcode!(Mov,  None, DL, Imm8, WO, RO),
    /* b3 */ opcode!(Mov,  None, BL, Imm8, WO, RO),
    /* b4 */ opcode!(Mov,  None, AH, Imm8, WO, RO),
    /* b5 */ opcode!(Mov,  None, CH, Imm8, WO, RO),
    /* b6 */ opcode!(Mov,  None, DH, Imm8, WO, RO),
    /* b7 */ opcode!(Mov,  None, BH, Imm8, WO, RO),
    /* b8 */ opcode!(Mov,  None, AX, Imm16, WO, RO),
    /* b9 */ opcode!(Mov,  None, CX, Imm16, WO, RO),
    /* ba */ opcode!(Mov,  None, DX, Imm16, WO, RO),
    /* bb */ opcode!(Mov,  None, BX, Imm16, WO, RO),
    /* bc */ opcode!(Mov,  None, SP, Imm16, WO, RO),
    /* bd */ opcode!(Mov,  None, BP, Imm16, WO, RO),
    /* be */ opcode!(Mov,  None, SI, Imm16, WO, RO),
    /* bf */ opcode!(Mov,  None, DI, Imm16, WO, RO),
    /* c0 */ group!(               RM8,  Imm8, WO, RO),
    /* c1 */ group!(               RM16, Imm8, WO, RO),
    /* c2 */ opcode!(Ret,  None, Imm16, RO),
    /* c3 */ opcode!(Ret),
    /* c4 */ opcode!(Les,  ModRM, Reg16, Mem32, WO, RO),
    /* c5 */ opcode!(Lds,  ModRM, Reg16, Mem32, WO, RO),
    /* c6 */ opcode!(Mov,  ModRM, RM8, Imm8, WO, RO),
    /* c7 */ opcode!(Mov,  ModRM, RM16, Imm16, WO, RO),
    /* c8 */ None,
    /* c9 */ None,
    /* ca */ opcode!(Retf, None, Imm16, RO),
    /* cb */ opcode!(Retf),
    /* cc */ opcode!(Int,  None, Const3, RO),
    /* cd */ opcode!(Int,  None, Imm8, RO),
    /* ce */ opcode!(Into),
    /* cf */ opcode!(Iret),
    /* d0 */ group!(         RM8,  Const1, RW, RO),
    /* d1 */ group!(         RM16, Const1, RW, RO),
    /* d2 */ group!(         RM8,  CL,     RW, RO),
    /* d3 */ group!(         RM16, CL,     RW, RO),
    /* d4 */ opcode!(Aam,  None, Imm8,   RO),
    /* d5 */ opcode!(Aad,  None, Imm8,   RO),
    /* d6 */ None,
    /* d7 */ opcode!(Xlat),
    /* d8 */ None,
    /* d9 */ None,
    /* da */ None,
    /* db */ None,
    /* dc */ None,
    /* dd */ None,
    /* de */ None,
    /* df */ None,
    /* e0 */ opcode!(Loopnz, None, Rel8, RO),
    /* e1 */ opcode!(Loopz,  None, Rel8, RO),
    /* e2 */ opcode!(Loop,   None, Rel8, RO),
    /* e3 */ opcode!(Jcxz,   None, Rel8, RO),
    /* e4 */ opcode!(In,     None, AL, Imm8, WO, RO),
    /* e5 */ opcode!(In,     None, AX, Imm8, WO, RO),
    /* e6 */ opcode!(Out,    None, Imm8, AL, RO, RO),
    /* e7 */ opcode!(Out,    None, Imm8, AX, RO, RO),
    /* e8 */ opcode!(Call,   None, Rel16,  RO),
    /* e9 */ opcode!(Jmp,    None, Rel16,  RO),
    /* ea */ opcode!(Jmp,    None, IMem32, RO),
    /* eb */ opcode!(Jmp,    None, Rel8,   RO),
    /* ec */ opcode!(In,     None, AL, DX, WO, RO),
    /* ed */ opcode!(In,     None, AX, DX, WO, RO),
    /* ee */ opcode!(Out,    None, DX, AL, RO, RO),
    /* ef */ opcode!(Out,    None, DX, AX, RO, RO),
    /* f0 */ opcode!(Lock),
    /* f1 */ None,
    /* f2 */ None,
    /* f3 */ None,
    /* f4 */ opcode!(Hlt),
    /* f5 */ opcode!(Cmc),
    /* f6 */ group!(RM8,  Imm8,  RW, RO),
    /* f7 */ group!(RM16, Imm16, RW, RO),
    /* f8 */ opcode!(Clc),
    /* f9 */ opcode!(Stc),
    /* fa */ opcode!(Cli),
    /* fb */ opcode!(Sti),
    /* fc */ opcode!(Cld),
    /* fd */ opcode!(Std),
    /* fe */ group!(RM8, RW),
    /* ff */ group!(),
];

#[rustfmt::skip]
pub static GROUP_1: [Option<Instruction>; 8] = [
    opcode!(Add, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Or,  None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Adc, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Sbb, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(And, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Sub, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Xor, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Cmp, None, Inherit, Inherit, RO, RO),
];

pub static GROUP_2: [Option<Instruction>; 8] = [
    opcode!(Rol, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Ror, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Rcl, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Rcr, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Shl, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Shr, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Sal, None, Inherit, Inherit, Inherit, Inherit),
    opcode!(Sar, None, Inherit, Inherit, Inherit, Inherit),
];

#[rustfmt::skip]
pub static GROUP_3: [Option<Instruction>; 8] = [
    opcode!(Test, None, Inherit, Inherit, RO, RO),
    opcode!(Test, None, Inherit, Inherit, RO, RO),
    opcode!(Not,  None, Inherit, RW),
    opcode!(Neg,  None, Inherit, RW),
    opcode!(Mul,  None, Inherit, RW),
    opcode!(Imul, None, Inherit, RW),
    opcode!(Div,  None, Inherit, RW),
    opcode!(Idiv, None, Inherit, RW),
];

pub static GROUP_4: [Option<Instruction>; 8] = [
    opcode!(Inc, None, Inherit, Inherit),
    opcode!(Dec, None, Inherit, Inherit),
    None,
    None,
    None,
    None,
    None,
    opcode!(ChaniCallback),
];

#[rustfmt::skip]
pub static GROUP_5: [Option<Instruction>; 8] = [
    opcode!(Inc,  None, RM16, RW),
    opcode!(Dec,  None, RM16, RW),
    opcode!(Call, None, RM16, RO),
    opcode!(Call, None, RM16, RO),
    opcode!(Jmp,  None, RM16, RO),
    opcode!(Jmp,  None, RM16, RO),
    opcode!(Push, None, RM16, RO),
    None,
];
