[package]
name = "chani_tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chani_tui"
path = "src/main.rs"

[dependencies]
chani_disasm = { path = "../chani_disasm" }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
ratatui.workspace = true
crossterm.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
