#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ArgType {
    Inherit,
    None,
    Const1,
    Const3,
    AL,
    CL,
    DL,
    BL,
    AH,
    CH,
    DH,
    BH,
    AX,
    CX,
    DX,
    BX,
    SP,
    BP,
    SI,
    DI,
    ES,
    CS,
    SS,
    DS,
    Reg8,
    Reg16,
    SReg,
    Imm8,
    Imm16,
    Rel8,
    Rel16,
    IMem8,
    IMem16,
    IMem32,
    // Mem8,
    Mem16,
    Mem32,
    RM8,
    RM16,
}

impl ArgType {
    pub fn needs_width_specifier(&self) -> bool {
        matches!(self, Self::None | Self::Imm8 | Self::Imm16)
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ArgDir {
    None,
    RO = 1, // Read only
    RW,     // Read/write
    WO,     // Write only
    Inherit,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Flag {
    None,
    ModRM,
    Group,
}

#[derive(Clone, Debug)]
pub struct Instruction {
    pub mnemonic: &'static str,
    pub flag: Flag,
    pub arg_type: [ArgType; 2],
    pub arg_dir: [ArgDir; 2],
}

impl Instruction {
    pub fn needs_modrm(&self) -> bool {
        matches!(self.flag, Flag::ModRM | Flag::Group)
    }
}

macro_rules! group {
    () => {
        Some(Instruction {
            mnemonic: "",
            flag: Flag::Group,
            arg_type: [ArgType::None, ArgType::None],
            arg_dir: [ArgDir::None, ArgDir::None],
        })
    };
    ($arg1ty:tt, $arg1dir:tt) => {
        Some(Instruction {
            mnemonic: "",
            flag: Flag::Group,
            arg_type: [ArgType::$arg1ty, ArgType::None],
            arg_dir: [ArgDir::$arg1dir, ArgDir::None],
        })
    };
    ($arg1ty:tt, $arg2ty:tt, $arg1dir:tt, $arg2dir:tt) => {
        Some(Instruction {
            mnemonic: "",
            flag: Flag::Group,
            arg_type: [ArgType::$arg1ty, ArgType::$arg2ty],
            arg_dir: [ArgDir::$arg1dir, ArgDir::$arg2dir],
        })
    };
}

macro_rules! opcode {
    ($mn:literal) => {
        Some(Instruction {
            mnemonic: $mn,
            flag: Flag::None,
            arg_type: [ArgType::None, ArgType::None],
            arg_dir: [ArgDir::None, ArgDir::None],
        })
    };
    ($mn:literal, $flag:tt, $arg1ty:tt, $arg1dir:tt) => {
        Some(Instruction {
            mnemonic: $mn,
            flag: Flag::$flag,
            arg_type: [ArgType::$arg1ty, ArgType::None],
            arg_dir: [ArgDir::$arg1dir, ArgDir::None],
        })
    };
    ($mn:literal, $flag:tt, $arg1ty:tt, $arg2ty:tt, $arg1dir:tt, $arg2dir:tt) => {
        Some(Instruction {
            mnemonic: $mn,
            flag: Flag::$flag,
            arg_type: [ArgType::$arg1ty, ArgType::$arg2ty],
            arg_dir: [ArgDir::$arg1dir, ArgDir::$arg2dir],
        })
    };
}

#[rustfmt::skip]
pub static OPCODE_TABLE: [Option<Instruction>; 256] = [
    /* 00 */ opcode!("add",  ModRM, RM8, Reg8, RW, RO),
    /* 01 */ opcode!("add",  ModRM, RM16, Reg16, RW, RO),
    /* 02 */ opcode!("add",  ModRM, Reg8, RM8, RW, RO),
    /* 03 */ opcode!("add",  ModRM, Reg16, RM16, RW, RO),
    /* 04 */ opcode!("add",  None, AL, Imm8, RW, RO),
    /* 05 */ opcode!("add",  None, AX, Imm16, RW, RO),
    /* 06 */ opcode!("push", None, ES, RO),
    /* 07 */ opcode!("pop",  None, ES, WO),
    /* 08 */ opcode!("or",   ModRM, RM8, Reg8, RW, RO),
    /* 09 */ opcode!("or",   ModRM, RM16, Reg16, RW, RO),
    /* 0a */ opcode!("or",   ModRM, Reg8, RM8, RW, RO),
    /* 0b */ opcode!("or",   ModRM, Reg16, RM16, RW, RO),
    /* 0c */ opcode!("or",   None, AL, Imm8, RW, RO),
    /* 0d */ opcode!("or",   None, AX, Imm16, RW, RO),
    /* 0e */ opcode!("push", None, CS, RO),
    /* 0f */ opcode!("pop",  None, CS, WO),
    /* 10 */ opcode!("adc",  ModRM, RM8, Reg8, RW, RO),
    /* 11 */ opcode!("adc",  ModRM, RM16, Reg16, RW, RO),
    /* 12 */ opcode!("adc",  ModRM, Reg8, RM8, RW, RO),
    /* 13 */ opcode!("adc",  ModRM, Reg16, RM16, RW, RO),
    /* 14 */ opcode!("adc",  None, AL, Imm8, RW, RO),
    /* 15 */ opcode!("adc",  None, AX, Imm16, RW, RO),
    /* 16 */ opcode!("push", None, SS, RO),
    /* 17 */ opcode!("pop",  None, SS, RO),
    /* 18 */ opcode!("sbb",  ModRM, RM8, Reg8, RW, RO),
    /* 19 */ opcode!("sbb",  ModRM, RM16, Reg16, RW, RO),
    /* 1a */ opcode!("sbb",  ModRM, Reg8, RM8, RW, RO),
    /* 1b */ opcode!("sbb",  ModRM, Reg16, RM16, RW, RO),
    /* 1c */ opcode!("sbb",  None, AL, Imm8, RW, RO),
    /* 1d */ opcode!("sbb",  None, AX, Imm16, RW, RO),
    /* 1e */ opcode!("push", None, DS, RO),
    /* 1f */ opcode!("pop",  None, DS, WO),
    /* 20 */ opcode!("and",  ModRM, RM8, Reg8, RW, RO),
    /* 21 */ opcode!("and",  ModRM, RM16, Reg16, RW, RO),
    /* 22 */ opcode!("and",  ModRM, Reg8, RM8, RW, RO),
    /* 23 */ opcode!("and",  ModRM, Reg16, RM16, RW, RO),
    /* 24 */ opcode!("and",  None, AL, Imm8, RW, RO),
    /* 25 */ opcode!("and",  None, AX, Imm16, RW, RO),
    /* 26 */ None,
    /* 27 */ opcode!("daa"),
    /* 28 */ opcode!("sub",  ModRM, RM8, Reg8, RW, RO),
    /* 29 */ opcode!("sub",  ModRM, RM16, Reg16, RW, RO),
    /* 2a */ opcode!("sub",  ModRM, Reg8, RM8, RW, RO),
    /* 2b */ opcode!("sub",  ModRM, Reg16, RM16, RW, RO),
    /* 2c */ opcode!("sub",  None, AL, Imm8, RW, RO),
    /* 2d */ opcode!("sub",  None, AX, Imm16, RW, RO),
    /* 2e */ None,
    /* 2f */ opcode!("das"),
    /* 30 */ opcode!("xor",  ModRM, RM8, Reg8, RW, RO),
    /* 31 */ opcode!("xor",  ModRM, RM16, Reg16, RW, RO),
    /* 32 */ opcode!("xor",  ModRM, Reg8, RM8, RW, RO),
    /* 33 */ opcode!("xor",  ModRM, Reg16, RM16, RW, RO),
    /* 34 */ opcode!("xor",  None, AL, Imm8, RW, RO),
    /* 35 */ opcode!("xor",  None, AX, Imm16, RW, RO),
    /* 36 */ None,
    /* 37 */ opcode!("aaa"),
    /* 38 */ opcode!("cmp",  ModRM, RM8, Reg8, RO, RO),
    /* 39 */ opcode!("cmp",  ModRM, RM16, Reg16, RO, RO),
    /* 3a */ opcode!("cmp",  ModRM, Reg8, RM8, RO, RO),
    /* 3b */ opcode!("cmp",  ModRM, Reg16, RM16, RO, RO),
    /* 3c */ opcode!("cmp",  None, AL, Imm8, RO, RO),
    /* 3d */ opcode!("cmp",  None, AX, Imm16, RO, RO),
    /* 3e */ None,
    /* 3f */ opcode!("aas"),
    /* 40 */ opcode!("inc",  None, AX, RW),
    /* 41 */ opcode!("inc",  None, CX, RW),
    /* 42 */ opcode!("inc",  None, DX, RW),
    /* 43 */ opcode!("inc",  None, BX, RW),
    /* 44 */ opcode!("inc",  None, SP, RW),
    /* 45 */ opcode!("inc",  None, BP, RW),
    /* 46 */ opcode!("inc",  None, SI, RW),
    /* 47 */ opcode!("inc",  None, DI, RW),
    /* 48 */ opcode!("dec",  None, AX, RW),
    /* 49 */ opcode!("dec",  None, CX, RW),
    /* 4a */ opcode!("dec",  None, DX, RW),
    /* 4b */ opcode!("dec",  None, BX, RW),
    /* 4c */ opcode!("dec",  None, SP, RW),
    /* 4d */ opcode!("dec",  None, BP, RW),
    /* 4e */ opcode!("dec",  None, SI, RW),
    /* 4f */ opcode!("dec",  None, DI, RW),
    /* 50 */ opcode!("push", None, AX, RO),
    /* 51 */ opcode!("push", None, CX, RO),
    /* 52 */ opcode!("push", None, DX, RO),
    /* 53 */ opcode!("push", None, BX, RO),
    /* 54 */ opcode!("push", None, SP, RO),
    /* 55 */ opcode!("push", None, BP, RO),
    /* 56 */ opcode!("push", None, SI, RO),
    /* 57 */ opcode!("push", None, DI, RO),
    /* 58 */ opcode!("pop",  None, AX, WO),
    /* 59 */ opcode!("pop",  None, CX, WO),
    /* 5a */ opcode!("pop",  None, DX, WO),
    /* 5b */ opcode!("pop",  None, BX, WO),
    /* 5c */ opcode!("pop",  None, SP, WO),
    /* 5d */ opcode!("pop",  None, BP, WO),
    /* 5e */ opcode!("pop",  None, SI, WO),
    /* 5f */ opcode!("pop",  None, DI, WO),
    /* 60 */ None,
    /* 61 */ None,
    /* 62 */ None,
    /* 63 */ None,
    /* 64 */ None,
    /* 65 */ None,
    /* 66 */ None,
    /* 67 */ None,
    /* 68 */ None,
    /* 69 */ None,
    /* 6a */ None,
    /* 6b */ None,
    /* 6c */ None,
    /* 6d */ None,
    /* 6e */ None,
    /* 6f */ None,
    /* 70 */ opcode!("jo",   None, Rel8, RO),
    /* 71 */ opcode!("jno",  None, Rel8, RO),
    /* 72 */ opcode!("jb",   None, Rel8, RO),
    /* 73 */ opcode!("jnb",  None, Rel8, RO),
    /* 74 */ opcode!("jz",   None, Rel8, RO),
    /* 75 */ opcode!("jnz",  None, Rel8, RO),
    /* 76 */ opcode!("jbe",  None, Rel8, RO),
    /* 77 */ opcode!("ja",   None, Rel8, RO),
    /* 78 */ opcode!("js",   None, Rel8, RO),
    /* 79 */ opcode!("jns",  None, Rel8, RO),
    /* 7a */ opcode!("jpe",  None, Rel8, RO),
    /* 7b */ opcode!("jpo",  None, Rel8, RO),
    /* 7c */ opcode!("jl",   None, Rel8, RO),
    /* 7d */ opcode!("jge",  None, Rel8, RO),
    /* 7e */ opcode!("jle",  None, Rel8, RO),
    /* 7f */ opcode!("jg",   None, Rel8, RO),
    /* 80 */ group!(         RM8, Imm8, RW, RO),
    /* 81 */ group!(         RM16, Imm16, RW, RO),
    /* 82 */ group!(         RM8, Imm8, RW, RO),
    /* 83 */ group!(         RM16, Imm8, RW, RO),
    /* 84 */ opcode!("test", ModRM, Reg8, RM8, RO, RO),
    /* 85 */ opcode!("test", ModRM, Reg16, RM16, RO, RO),
    /* 86 */ opcode!("xchg", ModRM, Reg8, RM8, RW, RW),
    /* 87 */ opcode!("xchg", ModRM, Reg16, RM16, RW, RW),
    /* 88 */ opcode!("mov",  ModRM, RM8, Reg8, WO, RO),
    /* 89 */ opcode!("mov",  ModRM, RM16, Reg16, WO, RO),
    /* 8a */ opcode!("mov",  ModRM, Reg8, RM8, WO, RO),
    /* 8b */ opcode!("mov",  ModRM, Reg16, RM16, WO, RO),
    /* 8c */ opcode!("mov",  ModRM, RM16, SReg, WO, RO),
    /* 8d */ opcode!("lea",  ModRM, Reg16, Mem16, RO, RO),
    /* 8e */ opcode!("mov",  ModRM, SReg, RM16, WO, RO),
    /* 8f */ opcode!("pop",  ModRM, RM16, WO),
    /* 90 */ opcode!("nop"),
    /* 91 */ opcode!("xchg", None, CX, AX, RW, RW),
    /* 92 */ opcode!("xchg", None, DX, AX, RW, RW),
    /* 93 */ opcode!("xchg", None, BX, AX, RW, RW),
    /* 94 */ opcode!("xchg", None, SP, AX, RW, RW),
    /* 95 */ opcode!("xchg", None, BP, AX, RW, RW),
    /* 96 */ opcode!("xchg", None, SI, AX, RW, RW),
    /* 97 */ opcode!("xchg", None, DI, AX, RW, RW),
    /* 98 */ opcode!("cbw"),
    /* 99 */ opcode!("cwd"),
    /* 9a */ opcode!("call", None, IMem32, RO),
    /* 9b */ opcode!("wait"),
    /* 9c */ opcode!("pushf"),
    /* 9d */ opcode!("popf"),
    /* 9e */ opcode!("sahf"),
    /* 9f */ opcode!("lahf"),
    /* a0 */ opcode!("mov",  None, AL, IMem8, WO, RO),
    /* a1 */ opcode!("mov",  None, AX, IMem16, WO, RO),
    /* a2 */ opcode!("mov",  None, IMem8, AL, WO, RO),
    /* a3 */ opcode!("mov",  None, IMem16, AX, WO, RO),
    /* a4 */ opcode!("movsb"),
    /* a5 */ opcode!("movsw"),
    /* a6 */ opcode!("cmpsb"),
    /* a7 */ opcode!("cmpsw"),
    /* a8 */ opcode!("test", None, AL, Imm8, RO, RO),
    /* a9 */ opcode!("test", None, AX, Imm16, RO, RO),
    /* aa */ opcode!("stosb"),
    /* ab */ opcode!("stosw"),
    /* ac */ opcode!("lodsb"),
    /* ad */ opcode!("lodsw"),
    /* ae */ opcode!("scasb"),
    /* af */ opcode!("scasw"),
    /* b0 */ opcode!("mov",  None, AL, Imm8, WO, RO),
    /* b1 */ opcode!("mov",  None, CL, Imm8, WO, RO),
    /* b2 */ opcode!("mov",  None, DL, Imm8, WO, RO),
    /* b3 */ opcode!("mov",  None, BL, Imm8, WO, RO),
    /* b4 */ opcode!("mov",  None, AH, Imm8, WO, RO),
    /* b5 */ opcode!("mov",  None, CH, Imm8, WO, RO),
    /* b6 */ opcode!("mov",  None, DH, Imm8, WO, RO),
    /* b7 */ opcode!("mov",  None, BH, Imm8, WO, RO),
    /* b8 */ opcode!("mov",  None, AX, Imm16, WO, RO),
    /* b9 */ opcode!("mov",  None, CX, Imm16, WO, RO),
    /* ba */ opcode!("mov",  None, DX, Imm16, WO, RO),
    /* bb */ opcode!("mov",  None, BX, Imm16, WO, RO),
    /* bc */ opcode!("mov",  None, SP, Imm16, WO, RO),
    /* bd */ opcode!("mov",  None, BP, Imm16, WO, RO),
    /* be */ opcode!("mov",  None, SI, Imm16, WO, RO),
    /* bf */ opcode!("mov",  None, DI, Imm16, WO, RO),
    /* c0 */ group!(               RM8,  Imm8, WO, RO),
    /* c1 */ group!(               RM16, Imm8, WO, RO),
    /* c2 */ opcode!("ret",  None, Imm16, RO),
    /* c3 */ opcode!("ret"),
    /* c4 */ opcode!("les",  ModRM, Reg16, Mem32, WO, RO),
    /* c5 */ opcode!("lds",  ModRM, Reg16, Mem32, WO, RO),
    /* c6 */ opcode!("mov",  ModRM, RM8, Imm8, WO, RO),
    /* c7 */ opcode!("mov",  ModRM, RM16, Imm16, WO, RO),
    /* c8 */ None,
    /* c9 */ None,
    /* ca */ opcode!("retf", None, Imm16, RO),
    /* cb */ opcode!("retf"),
    /* cc */ opcode!("int",  None, Const3, RO),
    /* cd */ opcode!("int",  None, Imm8, RO),
    /* ce */ opcode!("into"),
    /* cf */ opcode!("iret"),
    /* d0 */ group!(         RM8,  Const1, RW, RO),
    /* d1 */ group!(         RM16, Const1, RW, RO),
    /* d2 */ group!(         RM8,  CL,     RW, RO),
    /* d3 */ group!(         RM16, CL,     RW, RO),
    /* d4 */ opcode!("aam",  None, Imm8,   RO),
    /* d5 */ opcode!("aad",  None, Imm8,   RO),
    /* d6 */ None,
    /* d7 */ opcode!("xlat"),
    /* d8 */ None,
    /* d9 */ None,
    /* da */ None,
    /* db */ None,
    /* dc */ None,
    /* dd */ None,
    /* de */ None,
    /* df */ None,
    /* e0 */ opcode!("loopnz", None, Rel8, RO),
    /* e1 */ opcode!("loopz",  None, Rel8, RO),
    /* e2 */ opcode!("loop",   None, Rel8, RO),
    /* e3 */ opcode!("jcxz",   None, Rel8, RO),
    /* e4 */ opcode!("in",     None, AL, Imm8, WO, RO),
    /* e5 */ opcode!("in",     None, AX, Imm8, WO, RO),
    /* e6 */ opcode!("out",    None, Imm8, AL, RO, RO),
    /* e7 */ opcode!("out",    None, Imm8, AX, RO, RO),
    /* e8 */ opcode!("call",   None, Rel16,  RO),
    /* e9 */ opcode!("jmp",    None, Rel16,  RO),
    /* ea */ opcode!("jmp",    None, IMem32, RO),
    /* eb */ opcode!("jmp",    None, Rel8,   RO),
    /* ec */ opcode!("in",     None, AL, DX, WO, RO),
    /* ed */ opcode!("in",     None, AX, DX, WO, RO),
    /* ee */ opcode!("out",    None, DX, AL, RO, RO),
    /* ef */ opcode!("out",    None, DX, AX, RO, RO),
    /* f0 */ opcode!("lock"),
    /* f1 */ None,
    /* f2 */ None,
    /* f3 */ None,
    /* f4 */ opcode!("hlt"),
    /* f5 */ opcode!("cmc"),
    /* f6 */ group!(RM8,  Imm8,  RW, RO),
    /* f7 */ group!(RM16, Imm16, RW, RO),
    /* f8 */ opcode!("clc"),
    /* f9 */ opcode!("stc"),
    /* fa */ opcode!("cli"),
    /* fb */ opcode!("sti"),
    /* fc */ opcode!("cld"),
    /* fd */ opcode!("std"),
    /* fe */ group!(RM8, RW),
    /* ff */ group!(),
];

#[rustfmt::skip]
pub static GROUP_1: [Option<Instruction>; 8] = [
    opcode!("add", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("or",  None, Inherit, Inherit, Inherit, Inherit),
    opcode!("adc", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("sbb", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("and", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("sub", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("xor", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("cmp", None, Inherit, Inherit, RO, RO),
];

pub static GROUP_2: [Option<Instruction>; 8] = [
    opcode!("rol", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("ror", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("rcl", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("rcr", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("shl", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("shr", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("sal", None, Inherit, Inherit, Inherit, Inherit),
    opcode!("sar", None, Inherit, Inherit, Inherit, Inherit),
];

#[rustfmt::skip]
pub static GROUP_3: [Option<Instruction>; 8] = [
    opcode!("test", None, Inherit, Inherit, RO, RO),
    opcode!("test", None, Inherit, Inherit, RO, RO),
    opcode!("not",  None, Inherit, RW),
    opcode!("neg",  None, Inherit, RW),
    opcode!("mul",  None, Inherit, RW),
    opcode!("imul", None, Inherit, RW),
    opcode!("div",  None, Inherit, RW),
    opcode!("idiv", None, Inherit, RW),
];

pub static GROUP_4: [Option<Instruction>; 8] = [
    opcode!("inc", None, Inherit, Inherit),
    opcode!("dec", None, Inherit, Inherit),
    None,
    None,
    None,
    None,
    None,
    opcode!("chani-callback"),
];

#[rustfmt::skip]
pub static GROUP_5: [Option<Instruction>; 8] = [
    opcode!("inc",  None, RM16, RW),
    opcode!("dec",  None, RM16, RW),
    opcode!("call", None, RM16, RO),
    opcode!("call", None, RM16, RO),
    opcode!("jmp",  None, RM16, RO),
    opcode!("jmp",  None, RM16, RO),
    opcode!("push", None, RM16, RO),
    None,
];
