mod architecure;
mod loadexpr;
mod parse;
mod segments;

use std::io;
use std::path::Path;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
};

use sha1::{Digest, Sha1};

use chani_datafile::ast::{self, Dict, Document, Item};
use chani_datafile::{SmallString, parser};

use crate::basic_block::{BasicBlock, BasicBlockMap};
use crate::branch_map::BranchMap;
use crate::data_type::{
    CompositeDataType, DataType, DisplayFmt, ScalarDataType, StructDef, StructField,
};
use crate::function_map::FunctionMap;
use crate::function_summary::FunctionSummaryMap;
use crate::int_descriptions::IntDescriptions;
use crate::project::architecure::Architecture;
use crate::project::loadexpr::LoadExpr;
use crate::seg_dataflow::SegDataflow;
use crate::simple_const_propagation::SimpleConstPropagation;
use crate::type_prop::TypeProp;
use crate::work_queue::WorkQueue;
use crate::{Address, MemRef, SymbolLookup, decode};
use crate::{address_attributes::AddressAttributes, exe_mz::ExeMz};

pub(crate) use parse::split_top_level_commas;
use parse::{
    UnresolvedStructDef, fmt_load_expr, fmt_u32, parse_attr, parse_attr_type_str, parse_file_def,
    parse_load_expr, parse_segment, parse_struct, resolve_structs, validate_no_struct_cycles,
};

pub use segments::{Segment, SegmentIdx, Segments};

#[derive(Debug, Clone)]
pub struct Hash {
    pub bytes: Vec<u8>,
}

pub type Assume = (SmallString, SmallString);
pub type Assumes = Vec<Assume>;
pub type Structs = Vec<StructDef>;

#[allow(unused)]
#[derive(Debug, Clone)]
pub struct Project {
    pub name: SmallString,
    pub files: Vec<FileDef>,
    pub arch: Architecture,
    pub segments: Segments,
    pub structs: Structs,
    pub attrs: BTreeMap<Address, Attr>,
    pub exe: Option<ExeMz>,
    pub images: Vec<BinImage>,
    /// EXE segment-relocation map, keyed by linear byte address
    /// (`reloc.seg as u32 * 16 + reloc.ofs as u32`). Each entry resolves the
    /// preliminary 16-bit segment value at that location to a project
    /// `SegmentIdx`. Built during `analyze()` from `exe.relocations`.
    pub imm_relocations: BTreeMap<u32, SegmentIdx>,
    pub branches: BranchMap,
    pub blocks: BasicBlockMap,
    pub functions: FunctionMap,
    pub seg_dataflow: SegDataflow,
    pub simple_const_propagation: SimpleConstPropagation,
    pub function_summary: FunctionSummaryMap,
    /// Per-address register/stack types propagated from `let`/`fn` bindings.
    pub type_prop: TypeProp,
    pub data_xrefs: BTreeMap<Address, BTreeSet<Address>>,
    /// Built-in interrupt documentation, parsed from `assets/*.dict`.
    pub int_descriptions: IntDescriptions,
    /// Display-only comments generated by `analyze()` — never serialized.
    pub auto_comments: BTreeMap<Address, String>,
    /// Free-form notes / attribution lines from the project file's
    /// top-level `notes = [[[ ... ]]]` property. Each entry is one line.
    /// Rendered into the listing header by `generate_file_header`.
    pub notes: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum FileFormat {
    Exe,
    Com,
    Bin,
}

impl FileFormat {
    fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "exe" => Ok(FileFormat::Exe),
            "com" => Ok(FileFormat::Com),
            "bin" => Ok(FileFormat::Bin),
            _ => Err(format!("unknown file format '{}'", s)),
        }
    }

    fn from_extension(path: &str) -> Self {
        match Path::new(path)
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.to_ascii_lowercase())
            .as_deref()
        {
            Some("exe") => FileFormat::Exe,
            Some("com") => FileFormat::Com,
            _ => FileFormat::Bin,
        }
    }

    fn as_str(&self) -> &'static str {
        match self {
            FileFormat::Exe => "exe",
            FileFormat::Com => "com",
            FileFormat::Bin => "bin",
        }
    }
}

#[derive(Debug, Clone)]
pub struct FileDef {
    pub name: SmallString,
    pub format: FileFormat,
    pub path: String,
    pub hash: Option<Hash>,
}

#[derive(Debug, Clone)]
pub struct BinImage {
    pub seg_idx: SegmentIdx,
    /// Within-segment offset where byte 0 of the file is placed.
    pub load_offset: u32,
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AttrType {
    Code,
    Data(DataType),
}

#[derive(Debug)]
pub struct FlatField {
    pub name: String,
    pub r#type: ScalarDataType,
    pub offset: usize,
}

impl AttrType {
    pub fn type_str(&self, segments: &Segments, structs: &Structs) -> String {
        match self {
            AttrType::Code => "code".to_owned(),
            AttrType::Data(d) => d.type_str(segments, structs),
        }
    }

    pub fn byte_size(&self, bytes: &[u8], structs: &Structs) -> usize {
        match self {
            AttrType::Code => unreachable!(),
            AttrType::Data(d) => d.byte_size(bytes, structs),
        }
    }

    pub fn as_data(&self) -> Option<&DataType> {
        match self {
            AttrType::Code => None,
            AttrType::Data(data_type) => Some(data_type),
        }
    }
}

#[allow(unused)]
#[derive(Debug, Clone, Hash)]
pub struct Attr {
    pub addr: Address,
    pub r#type: Option<AttrType>,
    pub name: Option<SmallString>,
    pub is_auto_label: bool,
    pub ofs_seg: Option<SegmentIdx>,
    pub comment: Option<String>,
    /// Assumed segment register values at this address.
    pub assume: Vec<(SmallString, SmallString)>,
    /// Per-operand display format for code instructions (operand 0 and 1).
    pub arg_fmts: [Option<DisplayFmt>; 2],
    /// Manually-supplied branch destinations for indirect or self-modifying
    /// branch instructions. When present, these are authoritative — they
    /// supersede any statically-resolved target during disassembly.
    pub targets: Vec<Address>,
    /// Direction-less `let` type assertions: each names a typed value living in
    /// a register/flag/stack slot, valid from this address onward. Seeds for
    /// type propagation.
    pub lets: Vec<crate::binding::Binding>,
    /// A `fn` signature on a function-entry attribute: a flat list of `in` /
    /// `out` / `inout` bindings. `None` when the attr carries no signature.
    pub signature: Option<Vec<crate::binding::Binding>>,
}

impl Attr {
    /// An attribute for `addr` with every annotation unset.
    pub fn new(addr: Address) -> Self {
        Attr {
            addr,
            r#type: None,
            name: None,
            is_auto_label: false,
            ofs_seg: None,
            comment: None,
            assume: Assumes::default(),
            arg_fmts: [None; 2],
            targets: Vec::new(),
            lets: Vec::new(),
            signature: None,
        }
    }

    /// Set (or, with `None`/empty, clear) the user label. Marks the attribute
    /// user-authored, so it is no longer treated as an auto-label.
    pub fn set_name(&mut self, name: Option<String>) {
        self.name = name.filter(|s| !s.is_empty());
        self.is_auto_label = false;
    }

    /// Set (or, with `None`/empty, clear) the comment.
    pub fn set_comment(&mut self, comment: Option<String>) {
        self.comment = comment.filter(|s| !s.is_empty());
    }

    /// Whether the attribute carries no annotation and can be dropped.
    pub fn is_empty(&self) -> bool {
        self.r#type.is_none()
            && self.name.is_none()
            && self.ofs_seg.is_none()
            && self.comment.is_none()
            && self.assume.is_empty()
            && self.arg_fmts == [None, None]
            && self.targets.is_empty()
            && self.lets.is_empty()
            && self.signature.is_none()
    }
}

// ── Project implementation ────────────────────────────────────────────────────

#[allow(unused)]
fn hexdump(buf: &[u8]) {
    for (i, chunk) in buf.chunks(16).enumerate() {
        // Print offset
        print!("{:08x}  ", i * 16);

        // Print hex bytes
        for (j, byte) in chunk.iter().enumerate() {
            print!("{:02x} ", byte);
            if j == 7 {
                print!(" ");
            }
        }

        // Pad if less than 16 bytes
        if chunk.len() < 16 {
            for j in chunk.len()..16 {
                print!("   ");
                if j == 7 {
                    print!(" ");
                }
            }
        }

        // Print ASCII representation
        print!(" |");
        for byte in chunk {
            let ch = if byte.is_ascii_graphic() || *byte == b' ' {
                *byte as char
            } else {
                '.'
            };
            print!("{}", ch);
        }
        println!("|");
    }
}

impl Project {
    /// Return a slice of bytes starting at `(seg_idx, ofs)`.
    ///
    /// For bin/com-backed segments this reads from the loaded `BinImage`.
    /// For EXE-backed segments this reads from the flat `exe.image`.
    pub fn bytes_at_seg(&self, seg_idx: SegmentIdx, ofs: u32) -> &[u8] {
        for img in &self.images {
            if img.seg_idx == seg_idx {
                return ofs
                    .checked_sub(img.load_offset)
                    .and_then(|o| img.data.get(o as usize..))
                    .unwrap_or(&[]);
            }
        }
        let start = self.segments[seg_idx].start.unwrap_or(0) as usize;
        self.exe
            .as_ref()
            .and_then(|e| e.image.get(start + ofs as usize..))
            .unwrap_or(&[])
    }

    /// Parse a project from a string without loading any binary files.
    /// Segments and structs are fully resolved; `images`, `exe`, and binary bytes are empty.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(content: &str) -> std::result::Result<Self, String> {
        let tokens = parser::parse(content)?;
        let doc = ast::Document::from_tokens(tokens)?;
        Project::from_document(doc)
    }

    pub fn from_project_file(path: &str) -> std::result::Result<Self, String> {
        let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
        let tokens = parser::parse(&content)?;
        let doc = ast::Document::from_tokens(tokens)?;
        let mut project = Project::from_document(doc)?;

        let base = Path::new(path).parent().unwrap_or(Path::new("."));

        // Load each binary file, validate or compute its SHA1 hash.
        let mut binary_data: Vec<Option<Vec<u8>>> = vec![None; project.files.len()];
        let mut computed_hashes: Vec<Vec<u8>> = Vec::with_capacity(project.files.len());
        for (i, file) in project.files.iter().enumerate() {
            let file_path = base.join(&file.path).to_string_lossy().into_owned();
            let data = fs::read(&file_path).map_err(|e| format!("{file_path}: {e}"))?;

            let computed = sha1_of(&data);
            if let Some(expected) = &file.hash {
                if expected.bytes != computed {
                    let exp: String = expected.bytes.iter().map(|b| format!("{b:02x}")).collect();
                    let got: String = computed.iter().map(|b| format!("{b:02x}")).collect();
                    return Err(format!(
                        "{}: hash mismatch\n  expected sha1:{exp}\n  actual   sha1:{got}",
                        file.path
                    ));
                }
            }
            computed_hashes.push(computed);

            match file.format {
                FileFormat::Exe => {
                    let exe = ExeMz::load(&data, file_path).map_err(|e| e.to_string())?;
                    project.exe = Some(exe);
                }
                FileFormat::Com | FileFormat::Bin => {
                    binary_data[i] = Some(data);
                }
            }
        }
        for (file, computed) in project.files.iter_mut().zip(computed_hashes) {
            if file.hash.is_none() {
                file.hash = Some(Hash { bytes: computed });
            }
        }

        // Apply segment load expressions.
        for (seg_idx, seg) in project.segments.indexed_iter_mut() {
            let load = match seg.load.clone() {
                Some(l) => l,
                None => continue,
            };

            let data = match project.files[load.file_idx].format {
                FileFormat::Exe => &project.exe.as_ref().unwrap().image,
                FileFormat::Com | FileFormat::Bin => binary_data[load.file_idx].as_ref().unwrap(),
            };

            let (seg_start, seg_end, file_start, file_end) = load
                .resolve(data.len() as u32)
                .map_err(|e| format!("load resolution error for segment '{}': {e}", seg.name))?;

            let image_data = data[file_start as usize..file_end as usize].to_vec();

            seg.start.get_or_insert(seg_start);
            seg.end.get_or_insert(seg_end);
            let size = seg.end.unwrap() - seg.start.unwrap();
            seg.addr_attributes = AddressAttributes::new_with_base(seg_start, size as usize);

            project.images.push(BinImage {
                seg_idx,
                load_offset: seg_start,
                data: image_data,
            });
        }

        Ok(project)
    }

    pub fn from_exe_file(exe_path: &str) -> std::result::Result<Self, String> {
        let data = fs::read(exe_path).map_err(|e| e.to_string())?;
        let exe = ExeMz::load(&data, exe_path.to_owned()).map_err(|e| e.to_string())?;
        let mut segments = make_segments(&exe);

        let file = FileDef {
            name: "exe".into(),
            format: FileFormat::Exe,
            path: exe_path.to_owned(),
            hash: None,
        };

        let mut images = Vec::new();

        for (seg_idx, seg) in segments.indexed_iter_mut() {
            let load = match seg.load.clone() {
                Some(l) => l,
                None => continue,
            };

            let data = &exe.image;

            let (seg_start, seg_end, file_start, file_end) = load
                .resolve(data.len() as u32)
                .map_err(|e| format!("load resolution error for segment '{}': {e}", seg.name))?;

            dbg!(seg_start, seg_end, file_start, file_end);

            let image_data = data[file_start as usize..file_end as usize].to_vec();

            seg.start.get_or_insert(seg_start);
            seg.end.get_or_insert(seg_end);
            let size = seg.end.unwrap() - seg.start.unwrap();
            seg.addr_attributes = AddressAttributes::new_with_base(seg_start, size as usize);

            images.push(BinImage {
                seg_idx,
                load_offset: seg_start,
                data: image_data,
            });
        }

        Ok(Project {
            name: SmallString::new(),
            files: vec![file],
            arch: Architecture::_8086,
            segments,
            structs: Vec::new(),
            attrs: BTreeMap::new(),
            exe: Some(exe),
            images,
            imm_relocations: BTreeMap::new(),
            branches: BranchMap::new(),
            blocks: BasicBlockMap::new(),
            functions: FunctionMap::new(),
            seg_dataflow: SegDataflow::new(),
            simple_const_propagation: SimpleConstPropagation::new(),
            function_summary: FunctionSummaryMap::new(),
            type_prop: TypeProp::new(),
            data_xrefs: BTreeMap::new(),
            int_descriptions: IntDescriptions::load_embedded(),
            auto_comments: BTreeMap::new(),
            notes: Vec::new(),
        })
    }

    pub fn from_document(doc: Document) -> Result<Self, String> {
        if doc.dicts.len() != 1 {
            return Err(format!(
                "expected exactly one top-level dict, found {}",
                doc.dicts.len()
            ));
        }
        let dict = doc.dicts.into_iter().next().unwrap();
        if dict.name != "project" {
            return Err(format!(
                "expected top-level 'project' dict, found '{}'",
                dict.name
            ));
        }
        Self::from_dict(dict)
    }

    fn from_dict(dict: Dict) -> Result<Self, String> {
        let name = dict.key.clone();
        let mut arch = Architecture::_8086;
        let mut notes: Vec<String> = Vec::new();

        let mut file_dicts: Vec<&Dict> = Vec::new();
        let mut segment_dicts: Vec<&Dict> = Vec::new();
        let mut struct_dicts: Vec<&Dict> = Vec::new();
        let mut attr_dicts: Vec<&Dict> = Vec::new();
        let mut unresolved_structs: BTreeMap<SmallString, UnresolvedStructDef> = BTreeMap::new();
        let mut attrs = BTreeMap::new();

        // Pass 1: collect dicts, parse simple properties.
        for item in &dict.items {
            match item {
                Item::Property { key, value, line } => match key.as_str() {
                    "arch" => arch = value.parse().map_err(|_| "Invalid architecture")?,
                    "notes" => notes.extend(value.lines().map(str::to_string)),
                    _ => {
                        return Err(format!(
                            "line {line}: unknown key '{}' in project '{}'",
                            key, name
                        ));
                    }
                },
                Item::Dict(nested) => match nested.name.as_str() {
                    "file" => file_dicts.push(nested),
                    "segment" => segment_dicts.push(nested),
                    "struct" => struct_dicts.push(nested),
                    "attr" => attr_dicts.push(nested),
                    _ => {
                        return Err(format!(
                            "line {}: invalid dict '{}'",
                            nested.line, nested.name
                        ));
                    }
                },
            }
        }

        // Pass 1.5: build Segment vec.
        let mut segments = Segments::default();
        let mut unresolved_loads: Vec<(SegmentIdx, SmallString, u32)> = Vec::new();
        for d in &segment_dicts {
            let (seg, load_str) = parse_segment(d)?;
            if let Some((ls, line)) = load_str {
                unresolved_loads.push((SegmentIdx::from(segments.len()), ls, line));
            }
            segments.push(seg);
        }

        // Resolve file dicts.
        let mut files: Vec<FileDef> = Vec::new();
        for d in file_dicts {
            files.push(parse_file_def(d)?);
        }

        // Resolve segment load expressions (needs binaries to be known).
        for (seg_idx, load_str, line) in unresolved_loads {
            let load = parse_load_expr(&load_str, &files).map_err(|e| {
                format!(
                    "line {line}: invalid load '{}' in segment '{}': {e}",
                    load_str, segments[seg_idx].name
                )
            })?;
            segments[seg_idx].load = Some(load);
        }

        // Pass 2: parse struct dicts.
        for d in struct_dicts {
            let (name, def) = parse_struct(d)?;
            unresolved_structs.insert(name, def);
        }
        validate_no_struct_cycles(&unresolved_structs)?;

        // Pass 3: resolve struct/segment names to indices.
        let structs = resolve_structs(unresolved_structs, &segments)?;
        let struct_names: Vec<SmallString> = structs.iter().map(|s| s.name.clone()).collect();

        // Pass 4: parse attr dicts.
        for d in attr_dicts {
            let attr = parse_attr(d, &segments, &struct_names)?;
            attrs.insert(attr.addr, attr);
        }

        Ok(Project {
            name,
            files,
            arch,
            segments,
            structs,
            attrs,
            exe: Default::default(),
            images: Vec::new(),
            imm_relocations: BTreeMap::new(),
            branches: BranchMap::new(),
            blocks: BasicBlockMap::new(),
            functions: FunctionMap::new(),
            seg_dataflow: SegDataflow::new(),
            simple_const_propagation: SimpleConstPropagation::new(),
            function_summary: FunctionSummaryMap::new(),
            type_prop: TypeProp::new(),
            data_xrefs: BTreeMap::new(),
            int_descriptions: IntDescriptions::load_embedded(),
            auto_comments: BTreeMap::new(),
            notes,
        })
    }

    pub fn write_to(&self, w: &mut impl io::Write) -> io::Result<()> {
        use chani_datafile::{BlockDict, InlineDict};

        let mut project = BlockDict::root("project", self.name.as_str());
        project.blank();
        project.prop("arch", &self.arch.to_string());
        if !self.notes.is_empty() {
            project.prop_encoded("notes", &self.notes.join("\n"));
        }
        project.blank();

        for bin in &self.files {
            let mut bin_dict = BlockDict::new("file", bin.name.as_str());
            bin_dict.prop("format", bin.format.as_str());
            bin_dict.prop("path", &bin.path);
            if let Some(hash) = &bin.hash {
                let hex: String = hash.bytes.iter().map(|b| format!("{b:02x}")).collect();
                bin_dict.prop("hash", &format!("sha1:{hex}"));
            }
            project.add_block(bin_dict);
            project.blank();
        }

        if !self.segments.is_empty() {
            for (seg_idx, seg) in self.segments.indexed_iter() {
                let bin_backed = self.images.iter().any(|img| img.seg_idx == seg_idx);
                let mut seg_dict = BlockDict::new("segment", seg.name.as_str());
                if let Some(t) = &seg.r#type {
                    seg_dict.prop("type", t.as_str());
                }
                if !bin_backed {
                    if let Some(start) = seg.start {
                        seg_dict.prop("start", &fmt_u32(start));
                    }
                    if let Some(end) = seg.end {
                        seg_dict.prop("end", &fmt_u32(end));
                    }
                } else {
                    // For binary-backed segments, only write `end` when it differs from the
                    // value the load expression would produce (e.g. BSS space beyond the file).
                    if let (Some(end), Some(img)) = (
                        seg.end,
                        self.images.iter().find(|img| img.seg_idx == seg_idx),
                    ) {
                        let derived_end = img.load_offset + img.data.len() as u32;
                        if end != derived_end {
                            seg_dict.prop("end", &fmt_u32(end));
                        }
                    }
                }
                if let Some(load) = &seg.load {
                    seg_dict.prop("load", &fmt_load_expr(load, &self.files));
                }
                if !seg.assume.is_empty() {
                    let assume_str = seg
                        .assume
                        .iter()
                        .map(|(sreg, seg)| format!("{sreg}:{seg}"))
                        .collect::<Vec<_>>()
                        .join(" ");
                    seg_dict.prop("assume", &assume_str);
                }
                project.add_block(seg_dict);
                project.blank();
            }
        }

        if !self.structs.is_empty() {
            for def in &self.structs {
                let mut struct_dict = BlockDict::new("struct", def.name.as_str());
                if let Some(comment) = &def.comment {
                    struct_dict.prop_encoded("comment", comment.as_str());
                }
                for field in &def.fields {
                    let mut field_dict = InlineDict::new("field", field.name.as_str());
                    field_dict.prop(
                        "type",
                        &field.r#type.type_str(&self.segments, &self.structs),
                    );
                    if let Some(comment) = &field.comment {
                        field_dict.prop_encoded("comment", comment.as_str());
                    }
                    struct_dict.add_inline(field_dict);
                }
                project.add_block(struct_dict);
                project.blank();
            }
        }

        if !self.attrs.is_empty() {
            for attr in self.attrs.values() {
                let key = format!("{}:{:04x}", self.segments[attr.addr.0].name, attr.addr.1);
                let mut attr_dict = InlineDict::new("attr", &key);
                if let Some(t) = &attr.r#type {
                    attr_dict.prop("type", &t.type_str(&self.segments, &self.structs));
                }
                if let Some(name) = &attr.name
                    && !attr.is_auto_label
                {
                    attr_dict.prop("name", name);
                }
                if let Some(ofs_seg) = attr.ofs_seg {
                    attr_dict.prop("ofs_seg", self.segments[ofs_seg].name.as_str());
                }
                if !attr.assume.is_empty() {
                    let assume_str = attr
                        .assume
                        .iter()
                        .map(|(sreg, seg)| format!("{sreg}:{seg}"))
                        .collect::<Vec<_>>()
                        .join(" ");
                    attr_dict.prop("assume", &assume_str);
                }
                if !attr.lets.is_empty() {
                    let s = crate::binding::binding_list_to_string(
                        &attr.lets,
                        &self.segments,
                        &self.structs,
                    );
                    attr_dict.prop_encoded("let", &s);
                }
                if let Some(signature) = &attr.signature {
                    let s = crate::binding::binding_list_to_string(
                        signature,
                        &self.segments,
                        &self.structs,
                    );
                    attr_dict.prop_encoded("fn", &s);
                }
                for (i, fmt) in attr.arg_fmts.iter().enumerate() {
                    if let Some(fmt) = fmt {
                        attr_dict.prop(format!("arg[{i}]"), fmt.as_str());
                    }
                }
                if !attr.targets.is_empty() {
                    let mut sorted: Vec<Address> = attr.targets.clone();
                    sorted.sort_by(|a, b| {
                        self.segments[a.0]
                            .name
                            .cmp(&self.segments[b.0].name)
                            .then(a.1.cmp(&b.1))
                    });
                    sorted.dedup();
                    let s = sorted
                        .iter()
                        .map(|(seg, ofs)| format!("{}:{:04x}", self.segments[*seg].name, ofs))
                        .collect::<Vec<_>>()
                        .join(", ");
                    attr_dict.prop("targets", &s);
                }
                if let Some(comment) = &attr.comment {
                    attr_dict.prop_encoded("comment", comment.as_str());
                }
                if !attr_dict.is_empty() {
                    project.add_inline(attr_dict);
                }
            }
            project.blank();
        }

        project.write_to(w)
    }

    pub fn analyze(&mut self) {
        self.build_imm_relocations();
        self.mark_data_attributes();
        self.disassemble();
        self.build_basic_blocks();

        // Const propagation runs early so we can recognise terminating `int`
        // sites and patch the block graph before any pass that consumes it.
        self.simple_const_propagation();
        self.apply_terminating_ints();

        self.functions = crate::function_map::compute(self);
        self.function_summary = crate::function_summary::compute(self);
        self.seg_dataflow = crate::seg_dataflow::compute(self);
        self.type_prop = crate::type_prop::compute(self);

        self.populate_int_auto_comments();
        self.generate_auto_labels();
        self.build_data_xrefs();
    }

    fn simple_const_propagation(&mut self) {
        self.simple_const_propagation = crate::simple_const_propagation::compute(self);
    }

    /// Treat `int` instructions whose pre-state matches a *terminating*
    /// [`IntDescription`] (e.g. `int 21h, AH=4Ch`) as flow-stoppers. After
    /// marking each as such, walk forward from the byte past the `int` and
    /// strip the code marks of any instruction that isn't reached by some
    /// other branch — those bytes were only decoded because the linear
    /// disassembler walked through what is in fact unreachable. Finally,
    /// rebuild the basic-block graph so downstream passes see the true CFG.
    fn apply_terminating_ints(&mut self) {
        let terminators: Vec<Address> = self
            .simple_const_propagation
            .int_sites
            .iter()
            .filter_map(|(addr, site)| {
                let desc = self.int_descriptions.find(site.vector, &site.state)?;
                desc.terminates.then_some(*addr)
            })
            .collect();

        if terminators.is_empty() {
            return;
        }

        for &(seg_idx, ofs) in &terminators {
            let attrs = &mut self.segments[seg_idx].addr_attributes;
            attrs.mark_as_stops_flow(ofs);
            let int_len = attrs.op_len(ofs);
            let mut cursor = ofs.wrapping_add(int_len);
            // Strip orphan instructions until we reach a known block start, a
            // data attr, or a byte that isn't an instruction head. A block
            // start means some other branch lands here, so the chunk is still
            // reachable and stays.
            loop {
                if attrs.is_block_start(cursor) || attrs.is_data(cursor) || !attrs.is_op(cursor) {
                    break;
                }
                let len = attrs.op_len(cursor);
                if len == 0 {
                    break;
                }
                attrs.unmark_as_code(cursor);
                cursor = cursor.wrapping_add(len);
            }
        }

        self.build_basic_blocks();
    }

    /// For every `int` site recognised by [`IntDescriptions`], drop a
    /// display-only block comment into [`Project::auto_comments`]. Comments
    /// here are never written back to the project file.
    fn populate_int_auto_comments(&mut self) {
        self.auto_comments.clear();
        for (addr, site) in &self.simple_const_propagation.int_sites {
            if let Some(desc) = self.int_descriptions.find(site.vector, &site.state) {
                self.auto_comments.insert(*addr, desc.format_comment());
            }
        }
    }

    /// Walk `self.exe.relocations` and translate each `(seg, ofs)` entry to a
    /// `(linear_address, SegmentIdx)` pair, using the preliminary 16-bit
    /// segment value the linker wrote at that location to look up the
    /// project segment via [`Project::segment_index_for`]. Relocations whose
    /// preliminary value doesn't match any project segment are skipped.
    fn build_imm_relocations(&mut self) {
        let Some(exe) = &self.exe else {
            self.imm_relocations = BTreeMap::new();
            return;
        };

        // Find which file index corresponds to the EXE, then build a
        // paragraph -> SegmentIdx map for every segment loaded from that
        // EXE. The load paragraph is `load.file_start / 16`.
        let exe_file_idx = self.files.iter().position(|f| f.format == FileFormat::Exe);
        let mut paragraph_to_seg: BTreeMap<u16, SegmentIdx> = BTreeMap::new();
        if let Some(exe_idx) = exe_file_idx {
            for (idx, s) in self.segments.indexed_iter() {
                let Some(load) = &s.load else { continue };
                if load.file_idx != exe_idx {
                    continue;
                }
                if load.file_start % 16 != 0 {
                    continue;
                }
                let paragraph = (load.file_start / 16) as u16;
                paragraph_to_seg.insert(paragraph, idx);
            }
        }

        let mut map = BTreeMap::new();
        for r in &exe.relocations {
            let lin = r.seg as u32 * 16 + r.ofs as u32;
            let Some(slot) = exe.image.get(lin as usize..lin as usize + 2) else {
                continue;
            };
            let prelim = u16::from_le_bytes([slot[0], slot[1]]);
            if let Some(&idx) = paragraph_to_seg.get(&prelim) {
                map.insert(lin, idx);
            }
        }
        self.imm_relocations = map;
    }

    fn build_data_xrefs(&mut self) {
        let pairs: Vec<(Address, Address)> = self
            .attrs
            .iter()
            .filter_map(|(&src, attr)| {
                let dt = attr.r#type.as_ref()?.as_data()?;
                let bytes = self.bytes_at_seg(src.0, src.1);
                let mut targets = Vec::new();
                collect_ofs16_targets(dt, bytes, &self.structs, attr.ofs_seg, &mut targets);
                Some(targets.into_iter().map(move |t| (t, src)))
            })
            .flatten()
            .collect();
        self.data_xrefs.clear();
        for (target, src) in pairs {
            self.data_xrefs.entry(target).or_default().insert(src);
        }
    }

    /// Mark all data-typed attributes in `addr_attributes` with their byte extents.
    pub fn mark_data_attributes(&mut self) {
        let addr_data_sizes: Vec<(Address, usize)> = self
            .attrs
            .iter()
            .filter_map(|(&addr, attr)| {
                let data_type = attr.r#type.as_ref().and_then(|typ| typ.as_data())?;
                Some((addr, data_type))
            })
            .map(|(addr, data_type)| {
                let bytes = self.bytes_at_seg(addr.0, addr.1);
                let size = data_type.byte_size(bytes, &self.structs).max(1);
                (addr, size)
            })
            .collect();

        for (addr, size) in addr_data_sizes {
            self.segments[addr.0]
                .addr_attributes
                .mark_as_data(addr.1, size as u32);
        }
    }

    /// Run the recursive disassembly pass.
    pub fn disassemble(&mut self) {
        let mut queue: WorkQueue<Address> = WorkQueue::new();
        let mut branches = BranchMap::new();

        let mut seeds: Vec<Address> = Vec::new();

        if let Some(exe) = &self.exe {
            if let Some(seg_idx) = self.segment_index_for(exe.head.cs) {
                seeds.push((seg_idx, exe.head.ip as u32));
            }
        }

        let code_seeds: Vec<Address> = self
            .attrs
            .values()
            .filter(|a| a.r#type == Some(AttrType::Code))
            .map(|a| a.addr)
            .collect();

        seeds.extend(code_seeds);

        let manual_target_seeds: Vec<Address> = self
            .attrs
            .values()
            .flat_map(|a| a.targets.iter().copied())
            .collect();

        seeds.extend(manual_target_seeds);

        for addr in seeds {
            queue.push(addr);
            self.segments[addr.0]
                .addr_attributes
                .mark_as_block_start(addr.1);
        }

        while let Some((seg_idx, ofs)) = queue.pop() {
            if !self.segments[seg_idx].addr_attributes.is_unmarked(ofs, 1) {
                continue;
            }

            let seg_val = (self.segments[seg_idx].start.unwrap_or(0) / 16) as u16;
            let mut cur_ofs = ofs;

            loop {
                let ctx = crate::DisasmCtx {
                    imm_relocations: Some(&self.imm_relocations),
                };
                let Some(inst) = crate::decode_with_ctx(
                    seg_val,
                    cur_ofs as u16,
                    self.bytes_at_seg(seg_idx, cur_ofs).iter().copied(),
                    &ctx,
                ) else {
                    break;
                };

                let len = inst.bytes.len() as u32;
                self.segments[seg_idx]
                    .addr_attributes
                    .mark_as_code(cur_ofs, len);

                let manual_targets: Vec<Address> = self
                    .attrs
                    .get(&(seg_idx, cur_ofs))
                    .map(|a| a.targets.clone())
                    .unwrap_or_default();

                if !manual_targets.is_empty() && !inst.branches() {
                    eprintln!(
                        "warning: targets specified at {}:{:04x} but instruction is not a branch",
                        self.segments[seg_idx].name, cur_ofs
                    );
                }

                if inst.branches() {
                    if !manual_targets.is_empty() {
                        // Manual targets are authoritative — they replace any
                        // statically-resolved destination (relevant for indirect
                        // branches and self-modifying jumps).
                        for target in &manual_targets {
                            branches.add((seg_idx, cur_ofs), *target);
                            queue.push(*target);
                            self.segments[target.0]
                                .addr_attributes
                                .mark_as_block_start(target.1);
                        }
                    } else if let Some((dst_seg, dst_ofs)) = inst.branch_destination() {
                        if let Some(dst_idx) = self.segment_index_for(dst_seg) {
                            branches.add((seg_idx, cur_ofs), (dst_idx, dst_ofs as u32));
                            queue.push((dst_idx, dst_ofs as u32));
                            self.segments[dst_idx]
                                .addr_attributes
                                .mark_as_block_start(dst_ofs as u32);
                        }
                    }
                    if !inst.stops_control_flow() {
                        // Fall-through of a conditional branch / call is a new block start.
                        let fall_through = cur_ofs.wrapping_add(len);
                        self.segments[seg_idx]
                            .addr_attributes
                            .mark_as_block_start(fall_through);
                    }
                }

                if inst.stops_control_flow() {
                    self.segments[seg_idx]
                        .addr_attributes
                        .mark_as_stops_flow(cur_ofs);
                    break;
                }

                cur_ofs = cur_ofs.wrapping_add(len);
            }
        }

        self.branches = branches;
    }

    /// Build the basic block map from the results of `disassemble()`.
    /// Must be called after `disassemble()`.
    pub fn build_basic_blocks(&mut self) {
        struct PendingBlock {
            seg_idx: SegmentIdx,
            start: u32,
            end: u32,
            last_instr: u32,
            has_fall_through: bool,
        }

        let mut pending: Vec<PendingBlock> = Vec::new();

        for (seg_idx, seg) in self.segments.indexed_iter_mut() {
            let attrs = &seg.addr_attributes;
            let base = attrs.base();

            let mut block_start: Option<u32> = None;
            let mut last_instr: u32 = base;

            let mut ofs_opt = if attrs.is_op(base) {
                Some(base)
            } else {
                attrs.next(base)
            };

            while let Some(ofs) = ofs_opt {
                let attrs = &seg.addr_attributes;

                if !attrs.is_op(ofs) {
                    // Hit data or unmarked — close any open block without fall-through.
                    if let Some(start) = block_start.take() {
                        let end = last_instr + attrs.op_len(last_instr);
                        pending.push(PendingBlock {
                            seg_idx,
                            start,
                            end,
                            last_instr,
                            has_fall_through: false,
                        });
                    }
                    ofs_opt = attrs.next(ofs);
                    continue;
                }

                if attrs.is_block_start(ofs) {
                    if let Some(start) = block_start.take() {
                        // Close previous block; fall-through continues to ofs.
                        pending.push(PendingBlock {
                            seg_idx,
                            start,
                            end: ofs,
                            last_instr,
                            has_fall_through: true,
                        });
                    }
                    block_start = Some(ofs);
                }

                last_instr = ofs;

                if attrs.stops_flow(ofs) {
                    if let Some(start) = block_start.take() {
                        let end = ofs + attrs.op_len(ofs);
                        pending.push(PendingBlock {
                            seg_idx,
                            start,
                            end,
                            last_instr: ofs,
                            has_fall_through: false,
                        });
                    }
                }

                ofs_opt = attrs.next(ofs);
            }

            // Close any block still open at segment end.
            if let Some(start) = block_start {
                let attrs = &seg.addr_attributes;
                let end = last_instr + attrs.op_len(last_instr);
                pending.push(PendingBlock {
                    seg_idx,
                    start,
                    end,
                    last_instr,
                    has_fall_through: false,
                });
            }
        }

        // Build block entries with successors.
        let mut map = BasicBlockMap::new();
        for pb in &pending {
            let last_addr = (pb.seg_idx, pb.last_instr);
            let mut successors: smallvec::SmallVec<[Address; 2]> =
                self.branches.targets(last_addr).collect();
            if pb.has_fall_through {
                successors.push((pb.seg_idx, pb.end));
            }
            map.insert(BasicBlock {
                seg_idx: pb.seg_idx,
                start: pb.start,
                end: pb.end,
                successors,
                predecessors: Vec::new(),
            });
        }

        // Invert successor edges to populate predecessors.
        let edges: Vec<(Address, Address)> = map
            .blocks()
            .flat_map(|b| {
                let from = (b.seg_idx, b.start);
                b.successors.iter().map(move |&to| (to, from))
            })
            .collect();

        for (to, from) in edges {
            if let Some(block) = map.block_at_mut(to.0, to.1) {
                block.predecessors.push(from);
            }
        }

        self.blocks = map;
    }

    /// Generate automatic labels for branch targets and typed-but-unnamed addresses.
    pub fn generate_auto_labels(&mut self) {
        let label_suffix = |seg_idx: SegmentIdx, ofs: u32| -> String {
            let is_bin = self.segments[seg_idx]
                .load
                .as_ref()
                .is_some_and(|l| matches!(self.files[l.file_idx].format, FileFormat::Bin));
            if is_bin {
                format!("{}_{:05x}", self.segments[seg_idx].name, ofs)
            } else if self.images.iter().any(|img| img.seg_idx == seg_idx) {
                format!("{ofs:05x}")
            } else {
                let seg = self.segments[seg_idx].start.unwrap_or(0) / 16;
                format!("{:05x}", seg * 16 + ofs)
            }
        };

        for (seg_idx, ofs) in self.branches.all_targets() {
            let label = format!("loc_{}", label_suffix(seg_idx, ofs));
            Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
        }

        let code_addrs: Vec<Address> = self
            .attrs
            .values()
            .filter(|a| a.r#type == Some(AttrType::Code) && a.name.is_none())
            .map(|a| a.addr)
            .collect();
        for (seg_idx, ofs) in code_addrs {
            let label = format!("loc_{}", label_suffix(seg_idx, ofs));
            Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
        }

        {
            let data_addrs: Vec<Address> = self
                .attrs
                .values()
                .filter(|a| a.name.is_none() && matches!(a.r#type, Some(AttrType::Data(_))))
                .map(|a| a.addr)
                .collect();
            for (seg_idx, ofs) in data_addrs {
                let label = format!("data_{}", label_suffix(seg_idx, ofs));
                Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
            }
        }

        // Collect all ofs16 targets (direct or inside composites) and label them.
        {
            let ofs16_info: Vec<(SegmentIdx, u32, DataType, Option<SegmentIdx>)> = self
                .attrs
                .values()
                .filter_map(|attr| {
                    if let Some(AttrType::Data(ref d)) = attr.r#type {
                        Some((attr.addr.0, attr.addr.1, d.clone(), attr.ofs_seg))
                    } else {
                        None
                    }
                })
                .collect();
            let mut ofs16_targets: Vec<Address> = Vec::new();
            for (seg_idx, ofs, data_type, fallback_seg) in &ofs16_info {
                let bytes = self.bytes_at_seg(*seg_idx, *ofs);
                collect_ofs16_targets(
                    data_type,
                    bytes,
                    &self.structs,
                    *fallback_seg,
                    &mut ofs16_targets,
                );
            }
            for (seg_idx, ofs) in ofs16_targets {
                let label = format!("data_{}", label_suffix(seg_idx, ofs));
                Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
            }
        }

        // Collect immediate instruction arguments with a specified ofs_seg
        {
            let mut imm_targets: Vec<Address> = Vec::new();
            for (seg_idx, seg) in self.segments.indexed_iter() {
                let seg_start = seg.start.unwrap_or(0);

                let mut ofs_opt = {
                    let base = seg.addr_attributes.base();
                    if seg.addr_attributes.is_op(base) {
                        Some(base)
                    } else {
                        seg.addr_attributes.next(base)
                    }
                };

                while let Some(ofs) = ofs_opt {
                    if !seg.addr_attributes.is_op(ofs) {
                        ofs_opt = seg.addr_attributes.next(ofs);
                        continue;
                    }

                    if let Some(ofs_seg) = self.attrs.get(&(seg_idx, ofs)).and_then(|a| a.ofs_seg) {
                        let seg_val = (seg_start / 16) as u16;
                        let bytes = self.bytes_at_seg(seg_idx, ofs);
                        if let Some(inst) = decode(seg_val, ofs as u16, bytes.iter().copied()) {
                            for (i, &arg_type) in inst.arg_type.iter().enumerate() {
                                if matches!(
                                    arg_type,
                                    crate::opcode_table::ArgType::Imm8
                                        | crate::opcode_table::ArgType::Imm16
                                ) {
                                    imm_targets.push((ofs_seg, inst.imm[i]));
                                }
                            }
                        }
                    }

                    ofs_opt = seg.addr_attributes.next(ofs);
                }
            }
            for (seg_idx, ofs) in imm_targets {
                let label = format!("data_{}", label_suffix(seg_idx, ofs));
                Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
            }
        }

        // Collect auto-label candidates from static memory references in code,
        // resolved via segment dataflow analysis.
        {
            let mut static_mem_targets: Vec<Address> = Vec::new();
            for (seg_idx, seg) in self.segments.indexed_iter() {
                let base = seg.addr_attributes.base();
                let seg_start = seg.start.unwrap_or(0);

                let mut ofs_opt = if seg.addr_attributes.is_op(base) {
                    Some(base)
                } else {
                    seg.addr_attributes.next(base)
                };

                while let Some(ofs) = ofs_opt {
                    if !seg.addr_attributes.is_op(ofs) {
                        ofs_opt = seg.addr_attributes.next(ofs);
                        continue;
                    }

                    let seg_val = (seg_start / 16) as u16;
                    let bytes = self.bytes_at_seg(seg_idx, ofs);
                    if let Some(inst) = decode(seg_val, ofs as u16, bytes.iter().copied()) {
                        match inst.mem_ref() {
                            Some(MemRef::Indirect {
                                seg: sreg,
                                base: None,
                                index: None,
                                disp,
                                ..
                            }) => {
                                let resolved = self
                                    .seg_dataflow
                                    .state_at(self, seg_idx, ofs)
                                    .and_then(|state| state.to_sreg_map().get(sreg))
                                    .or_else(|| {
                                        // Dataflow didn't pin down this sreg.
                                        // Fall back to the containing segment's
                                        // `assume <reg>:<seg>` declaration.
                                        seg.assume.iter().find_map(|(reg, assume_seg)| {
                                            (reg.as_str() == sreg.as_str())
                                                .then(|| self.segment_by_name(assume_seg))
                                                .flatten()
                                        })
                                    });
                                if let Some(target_seg) = resolved {
                                    static_mem_targets.push((target_seg, disp as u32));
                                }
                            }
                            Some(MemRef::Direct {
                                seg,
                                ofs: target_ofs,
                                ..
                            }) => {
                                if let Some(target_seg) = self.segment_index_for(seg) {
                                    static_mem_targets.push((target_seg, target_ofs as u32));
                                }
                            }
                            _ => {}
                        }
                    }

                    ofs_opt = seg.addr_attributes.next(ofs);
                }
            }
            for (seg_idx, ofs) in static_mem_targets {
                let label = format!("data_{}", label_suffix(seg_idx, ofs));
                Self::ensure_auto_label(&mut self.attrs, seg_idx, ofs, label);
            }
        }
    }

    pub fn attr_at(&self, seg_idx: SegmentIdx, ofs: u32) -> Option<&Attr> {
        self.attrs.get(&(seg_idx, ofs))
    }

    pub fn name_at(&self, seg_idx: SegmentIdx, ofs: u32) -> Option<&str> {
        self.attr_at(seg_idx, ofs)?.name.as_deref()
    }

    /// Set (or clear) the user label at `addr`, dropping the attribute if this
    /// leaves it empty. The authoritative mutation behind a rename — shared with
    /// `chaniq set --name`.
    pub fn set_attr_name(&mut self, addr: Address, name: Option<String>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.set_name(name);
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Set (or clear) the comment at `addr`, dropping the attribute if this
    /// leaves it empty. Shared with `chaniq set --comment`.
    pub fn set_attr_comment(&mut self, addr: Address, comment: Option<String>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.set_comment(comment);
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Set (or clear) the assumed segment for an `ofs16` reference at `addr`,
    /// dropping the attribute if this leaves it empty. Mirrors
    /// `chaniq set --ofs-seg`.
    pub fn set_attr_ofs_seg(&mut self, addr: Address, ofs_seg: Option<SegmentIdx>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.ofs_seg = ofs_seg;
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Set (or, with `None`, clear) the code/data classification at `addr`,
    /// dropping the attribute if this leaves it empty. Mirrors
    /// `chaniq set --type`.
    pub fn set_attr_type(&mut self, addr: Address, ty: Option<AttrType>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.r#type = ty;
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Replace the direction-less `let` assertions at `addr` (an empty list
    /// clears them), dropping the attribute if this leaves it empty. Mirrors
    /// `chaniq set --let`.
    pub fn set_attr_lets(&mut self, addr: Address, lets: Vec<crate::binding::Binding>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.lets = lets;
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Set (or, with `None`, clear) the display format of operand `index`
    /// (0 or 1) at `addr`, dropping the attribute if this leaves it empty.
    /// Mirrors `chaniq set --arg`.
    pub fn set_attr_arg_fmt(&mut self, addr: Address, index: usize, fmt: Option<DisplayFmt>) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.arg_fmts[index] = fmt;
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Set (or, with `None`/empty, clear) the `fn` signature at `addr`, dropping
    /// the attribute if this leaves it empty. Mirrors `chaniq set --fn`.
    pub fn set_attr_signature(
        &mut self,
        addr: Address,
        signature: Option<Vec<crate::binding::Binding>>,
    ) {
        let attr = self.attrs.entry(addr).or_insert_with(|| Attr::new(addr));
        attr.signature = signature.filter(|s| !s.is_empty());
        if attr.is_empty() {
            self.attrs.remove(&addr);
        }
    }

    /// Parse a data-type string (any `DataType`; `code` is rejected) against
    /// this project's segments and structs. Used for struct-field type editing.
    pub fn parse_data_type(&self, s: &str) -> Result<DataType, String> {
        let struct_names: Vec<SmallString> = self.structs.iter().map(|s| s.name.clone()).collect();
        parse_data_type_str(s, &self.segments, &struct_names)
    }

    // ── Struct-table mutation ─────────────────────────────────────────────────
    //
    // Structs are project-level, not per-attr. `DataType::Composite(Struct(idx))`
    // stores an *index* into `self.structs`, so adds (push at the end) keep
    // existing indices stable, while a remove shifts later indices and must
    // re-point every reference. Serialization renders struct refs by *name*
    // (`type_str`), so in-memory indices need only be internally consistent.

    /// Add an empty struct named `name`, returning its index. Errors on an empty
    /// or duplicate name.
    pub fn add_struct(&mut self, name: &str) -> Result<usize, String> {
        let name = name.trim();
        if name.is_empty() {
            return Err("struct name must not be empty".to_owned());
        }
        if self.structs.iter().any(|s| s.name == name) {
            return Err(format!("a struct named '{name}' already exists"));
        }
        self.structs.push(StructDef {
            name: name.to_owned(),
            comment: None,
            fields: Vec::new(),
        });
        Ok(self.structs.len() - 1)
    }

    /// Rename the struct at `idx`. Errors on an empty or duplicate name.
    pub fn rename_struct(&mut self, idx: usize, name: &str) -> Result<(), String> {
        let name = name.trim();
        if name.is_empty() {
            return Err("struct name must not be empty".to_owned());
        }
        if self
            .structs
            .iter()
            .enumerate()
            .any(|(i, s)| i != idx && s.name == name)
        {
            return Err(format!("a struct named '{name}' already exists"));
        }
        self.structs[idx].name = name.to_owned();
        Ok(())
    }

    /// Remove the struct at `idx`. Errors while any attr type, `let`/`fn`
    /// binding, or other struct field still references it. On success, every
    /// struct index greater than `idx` shifts down by one across the project.
    pub fn remove_struct(&mut self, idx: usize) -> Result<(), String> {
        if idx >= self.structs.len() {
            return Err("no such struct".to_owned());
        }
        if self.any_data_type(|dt| data_type_references_struct(dt, idx)) {
            return Err(format!(
                "struct '{}' is still referenced",
                self.structs[idx].name
            ));
        }
        self.structs.remove(idx);
        self.for_each_data_type_mut(|dt| reindex_data_type_after_remove(dt, idx));
        Ok(())
    }

    /// Set field `field_idx` (or append, when `None`) of struct `idx` to
    /// `name: ty`. Errors on an empty/duplicate field name or if the change
    /// introduces a by-value reference cycle.
    pub fn set_struct_field(
        &mut self,
        idx: usize,
        field_idx: Option<usize>,
        name: &str,
        ty: DataType,
    ) -> Result<(), String> {
        let name = name.trim();
        if name.is_empty() {
            return Err("field name must not be empty".to_owned());
        }
        if self.structs[idx]
            .fields
            .iter()
            .enumerate()
            .any(|(i, f)| Some(i) != field_idx && f.name == name)
        {
            return Err(format!("a field named '{name}' already exists"));
        }
        // Preserve any existing comment when overwriting a field in place, so a
        // name/type edit doesn't discard its documentation.
        let comment = field_idx
            .and_then(|i| self.structs[idx].fields.get(i))
            .and_then(|f| f.comment.clone());
        let field = StructField {
            name: name.to_owned(),
            r#type: ty,
            comment,
        };
        let old = match field_idx {
            Some(i) => Some(std::mem::replace(&mut self.structs[idx].fields[i], field)),
            None => {
                self.structs[idx].fields.push(field);
                None
            }
        };
        if struct_has_cycle(&self.structs) {
            match (field_idx, old) {
                (Some(i), Some(prev)) => self.structs[idx].fields[i] = prev,
                (None, _) => {
                    self.structs[idx].fields.pop();
                }
                _ => {}
            }
            return Err("that field would create a struct reference cycle".to_owned());
        }
        Ok(())
    }

    /// Set (or, with `None`/empty, clear) the comment on struct `idx`.
    pub fn set_struct_comment(&mut self, idx: usize, comment: Option<String>) {
        self.structs[idx].comment = comment.filter(|s| !s.is_empty());
    }

    /// Set (or, with `None`/empty, clear) the comment on field `field_idx` of
    /// struct `idx`.
    pub fn set_struct_field_comment(
        &mut self,
        idx: usize,
        field_idx: usize,
        comment: Option<String>,
    ) {
        self.structs[idx].fields[field_idx].comment = comment.filter(|s| !s.is_empty());
    }

    /// Remove field `field_idx` of struct `idx`.
    pub fn remove_struct_field(&mut self, idx: usize, field_idx: usize) -> Result<(), String> {
        if field_idx >= self.structs[idx].fields.len() {
            return Err("no such field".to_owned());
        }
        self.structs[idx].fields.remove(field_idx);
        Ok(())
    }

    /// Whether any `DataType` in the project satisfies `f`. Walks attr types,
    /// `let`/`fn` binding types, and struct field types.
    fn any_data_type(&self, mut f: impl FnMut(&DataType) -> bool) -> bool {
        for def in &self.structs {
            if def.fields.iter().any(|field| f(&field.r#type)) {
                return true;
            }
        }
        for attr in self.attrs.values() {
            if let Some(AttrType::Data(d)) = &attr.r#type
                && f(d)
            {
                return true;
            }
            if attr.lets.iter().any(|b| f(&b.ty)) {
                return true;
            }
            if let Some(sig) = &attr.signature
                && sig.iter().any(|b| f(&b.ty))
            {
                return true;
            }
        }
        false
    }

    /// Apply `f` to every `DataType` stored in the project (attr types,
    /// `let`/`fn` binding types, and struct field types).
    fn for_each_data_type_mut(&mut self, mut f: impl FnMut(&mut DataType)) {
        for def in &mut self.structs {
            for field in &mut def.fields {
                f(&mut field.r#type);
            }
        }
        for attr in self.attrs.values_mut() {
            if let Some(AttrType::Data(d)) = &mut attr.r#type {
                f(d);
            }
            for b in &mut attr.lets {
                f(&mut b.ty);
            }
            if let Some(sig) = &mut attr.signature {
                for b in sig {
                    f(&mut b.ty);
                }
            }
        }
    }

    /// Resolve an address to a label, preferring structured paths over flat names.
    ///
    /// Priority:
    /// 1. Exact user-supplied label at `(seg_idx, ofs)`
    /// 2. Array/struct path from a named typed attr that covers the address
    ///    (e.g. `locations[45]` or `locations[45].status`)
    /// 3. Exact auto-label at `(seg_idx, ofs)`
    pub fn resolve_label(&self, seg_idx: SegmentIdx, ofs: u32) -> Option<String> {
        if let Some(attr) = self.attr_at(seg_idx, ofs) {
            if let Some(name) = &attr.name {
                if !attr.is_auto_label {
                    return Some(name.clone());
                }
            }
        }
        if let Some(label) = self.resolve_typed_label(seg_idx, ofs) {
            return Some(label);
        }
        self.name_at(seg_idx, ofs).map(String::from)
    }

    /// Whether a register-indexed access `[sym + reg]` resolving to `ofs`
    /// denotes genuine array indexing.
    ///
    /// True when an array-typed label sits exactly at `ofs`, or when `ofs`
    /// falls inside a typed array/struct (the covering typed-path case). False
    /// for a scalar symbol at `ofs`: appending `[reg]` there would name an
    /// unrelated global that merely happens to live at that offset (e.g.
    /// `rand_bits[si]` for a pointer in `si`), so the caller should fall back
    /// to the raw `[base+index+disp]` form instead.
    fn is_register_indexable(&self, seg_idx: SegmentIdx, ofs: u32) -> bool {
        if let Some(attr) = self.attr_at(seg_idx, ofs)
            && attr.name.is_some()
        {
            return attr
                .r#type
                .as_ref()
                .and_then(|t| t.as_data())
                .is_some_and(|d| d.is_array());
        }
        self.resolve_typed_label(seg_idx, ofs).is_some()
    }

    fn resolve_typed_label(&self, seg_idx: SegmentIdx, ofs: u32) -> Option<String> {
        for (&(_, attr_ofs), attr) in self.attrs.range((seg_idx, 0)..=(seg_idx, ofs)).rev() {
            let rel = (ofs - attr_ofs) as usize;
            if rel == 0 {
                continue; // exact match already handled by resolve_label
            }
            let Some(name) = attr.name.as_deref().filter(|_| !attr.is_auto_label) else {
                continue;
            };
            let Some(dt) = attr.r#type.as_ref().and_then(|t| t.as_data()) else {
                continue;
            };
            if let Some(label) = path_in_type(dt, rel, name, &self.structs) {
                return Some(label);
            }
        }
        None
    }

    fn ensure_auto_label(
        attrs: &mut BTreeMap<Address, Attr>,
        seg_idx: SegmentIdx,
        ofs: u32,
        label: SmallString,
    ) {
        let key = (seg_idx, ofs);
        let existing = attrs.get(&key);
        if existing.is_some_and(|a| a.name.is_some()) {
            return;
        }
        let attr = attrs.entry(key).or_insert_with(|| Attr::new(key));
        attr.name = Some(label);
        attr.is_auto_label = true;
    }

    /// Parse a type string and resolve it against this project's segments and structs.
    pub fn parse_type_str(&self, s: &str) -> Result<AttrType, String> {
        let struct_names: Vec<SmallString> = self.structs.iter().map(|s| s.name.clone()).collect();
        parse_attr_type_str(s, &self.segments, &struct_names)
    }

    /// Resolve a byte offset into a (pointee) type to a field accessor path,
    /// e.g. `occupation`, `pos.x`, or `[3]` for an array element. Returns
    /// `None` if the offset falls outside the type or lands mid-field on a
    /// variable-size/scalar boundary. Packed layout (no gaps/unions) is assumed.
    ///
    /// Used by the listing renderer to rewrite `[si+3]` → `troop->occupation`
    /// when `si` carries a `*Troop` binding.
    pub fn field_path_in(&self, pointee: &DataType, offset: u32) -> Option<String> {
        let path = path_in_type(pointee, offset as usize, "", &self.structs)?;
        // `path_in_type` prefixes struct fields with '.'; strip the leading dot
        // so callers can compose `name->field` or `name[i]` themselves.
        Some(path.strip_prefix('.').unwrap_or(&path).to_string())
    }

    /// Find a segment by name.
    pub fn segment_by_name(&self, name: &str) -> Option<SegmentIdx> {
        self.segments
            .indexed_iter()
            .find(|(_, s)| s.name == name)
            .map(|(idx, _)| idx)
    }

    /// Look up an EXE-style segment register value → segment index.
    pub fn segment_index_for(&self, seg: u16) -> Option<SegmentIdx> {
        let target = seg as u32 * 16;
        for (idx, s) in self.segments.indexed_iter() {
            if s.start == Some(target) {
                return Some(idx);
            }
        }
        None
    }
}

// ── Struct-table helpers ──────────────────────────────────────────────────────

/// True if `dt` references struct index `k` anywhere within it.
fn data_type_references_struct(dt: &DataType, k: usize) -> bool {
    match dt {
        DataType::Composite(CompositeDataType::Struct(idx)) => *idx == k,
        DataType::Composite(CompositeDataType::Array { elem, .. }) => {
            data_type_references_struct(elem, k)
        }
        DataType::Formatted(_, inner) | DataType::Ptr(inner) => {
            data_type_references_struct(inner, k)
        }
        DataType::Tuple(members) => members.iter().any(|m| data_type_references_struct(m, k)),
        DataType::Scalar(_) => false,
    }
}

/// Decrement every struct index greater than `removed` within `dt`, after the
/// struct at index `removed` is deleted from the table.
fn reindex_data_type_after_remove(dt: &mut DataType, removed: usize) {
    match dt {
        DataType::Composite(CompositeDataType::Struct(idx)) => {
            if *idx > removed {
                *idx -= 1;
            }
        }
        DataType::Composite(CompositeDataType::Array { elem, .. }) => {
            reindex_data_type_after_remove(elem, removed)
        }
        DataType::Formatted(_, inner) | DataType::Ptr(inner) => {
            reindex_data_type_after_remove(inner, removed)
        }
        DataType::Tuple(members) => members
            .iter_mut()
            .for_each(|m| reindex_data_type_after_remove(m, removed)),
        DataType::Scalar(_) => {}
    }
}

/// Whether the struct table contains a by-value reference cycle. A near pointer
/// (`*T`) breaks the cycle — only `struct`/array/tuple/format containment counts,
/// matching the loader's `validate_no_struct_cycles` and `fixed_size` recursion.
fn struct_has_cycle(structs: &Structs) -> bool {
    #[derive(Clone, Copy, PartialEq)]
    enum Color {
        White,
        Gray,
        Black,
    }

    /// Struct indices `dt` contains by value (pointers excluded).
    fn deps(dt: &DataType, out: &mut Vec<usize>) {
        match dt {
            DataType::Composite(CompositeDataType::Struct(i)) => out.push(*i),
            DataType::Composite(CompositeDataType::Array { elem, .. }) => deps(elem, out),
            DataType::Formatted(_, inner) => deps(inner, out),
            DataType::Tuple(members) => members.iter().for_each(|m| deps(m, out)),
            DataType::Ptr(_) | DataType::Scalar(_) => {}
        }
    }

    fn visit(i: usize, structs: &Structs, color: &mut [Color]) -> bool {
        color[i] = Color::Gray;
        let mut neighbors = Vec::new();
        for f in &structs[i].fields {
            deps(&f.r#type, &mut neighbors);
        }
        for d in neighbors {
            match color[d] {
                Color::Gray => return true,
                Color::White => {
                    if visit(d, structs, color) {
                        return true;
                    }
                }
                Color::Black => {}
            }
        }
        color[i] = Color::Black;
        false
    }

    let mut color = vec![Color::White; structs.len()];
    (0..structs.len()).any(|i| color[i] == Color::White && visit(i, structs, &mut color))
}

// ── Structured label resolution helpers ──────────────────────────────────────

/// Returns the byte size of `dt` without reading any binary data.
/// Returns `None` for variable-size types (`cstr`, `unknown`).
fn fixed_size(dt: &DataType, structs: &Structs) -> Option<usize> {
    match dt {
        DataType::Scalar(ScalarDataType::CStr | ScalarDataType::Unknown) => None,
        DataType::Scalar(s) => Some(s.byte_size(&[])),
        DataType::Composite(CompositeDataType::Array { elem, count }) => {
            Some(fixed_size(elem, structs)? * count)
        }
        DataType::Composite(CompositeDataType::Struct(idx)) => {
            let def = &structs[*idx];
            let mut total = 0usize;
            for field in &def.fields {
                total += fixed_size(&field.r#type, structs)?;
            }
            Some(total)
        }
        DataType::Formatted(_, inner) => fixed_size(inner, structs),
        // Near pointer is 2 bytes; tuples are binding-only and have no fixed
        // data-layout size.
        DataType::Ptr(_) => Some(2),
        DataType::Tuple(_) => None,
    }
}

/// Build a label path for byte offset `rel` into type `dt` starting at `prefix`.
/// Returns `None` if `rel` is out of range or the type is variable-size.
fn path_in_type(dt: &DataType, rel: usize, prefix: &str, structs: &Structs) -> Option<String> {
    match dt {
        DataType::Composite(CompositeDataType::Array { elem, count }) => {
            let elem_size = fixed_size(elem, structs).filter(|&s| s > 0)?;
            let index = rel / elem_size;
            if index >= *count {
                return None;
            }
            let inner_rel = rel % elem_size;
            let indexed = format!("{prefix}[{index}]");
            if inner_rel == 0 {
                Some(indexed)
            } else {
                path_in_type(elem, inner_rel, &indexed, structs)
            }
        }
        DataType::Composite(CompositeDataType::Struct(idx)) => {
            let def = &structs[*idx];
            let mut cursor = 0usize;
            for field in &def.fields {
                let field_size = fixed_size(&field.r#type, structs)?;
                if rel >= cursor && rel < cursor + field_size {
                    let inner_rel = rel - cursor;
                    let field_path = format!("{prefix}.{}", field.name);
                    return if inner_rel == 0 {
                        Some(field_path)
                    } else {
                        path_in_type(&field.r#type, inner_rel, &field_path, structs)
                    };
                }
                cursor += field_size;
            }
            None
        }
        DataType::Formatted(_, inner) => path_in_type(inner, rel, prefix, structs),
        DataType::Scalar(_) | DataType::Ptr(_) => {
            if rel == 0 {
                Some(prefix.to_string())
            } else {
                None
            }
        }
        DataType::Tuple(_) => None,
    }
}

/// Parse and resolve a binding type string (any `DataType`; `code` is rejected).
/// Used by [`crate::binding`] when parsing `let`/`fn` bindings.
pub(crate) fn parse_data_type_str(
    s: &str,
    segments: &Segments,
    struct_names: &[SmallString],
) -> Result<DataType, String> {
    match parse_attr_type_str(s, segments, struct_names)? {
        AttrType::Data(d) => Ok(d),
        AttrType::Code => Err("'code' is not a valid binding type".to_owned()),
    }
}

// ── Symbol lookup ─────────────────────────────────────────────────────────────

/// The default display name for a location (its register/flag/stack spelling),
/// used when a binding is unnamed (`_`).
fn loc_default_name(loc: crate::binding::Location) -> String {
    use crate::binding::Location;
    match loc {
        Location::Gp16(r) => r.to_string(),
        Location::Gp8(r) => r.to_string(),
        Location::Seg(r) => r.to_string(),
        Location::Flag(f) => f.as_str().to_string(),
        Location::Stack(n) => format!("bp{n:+}"),
    }
}

pub struct ProjectLookup<'a> {
    pub project: &'a Project,
    pub sreg_map: crate::SRegMap,
    pub register_file: Option<crate::RegisterFile>,
    pub default_seg: Option<SegmentIdx>,
    /// Address of the instruction being rendered, used to query
    /// `type_prop` for binding-derived register/field names. `None` disables
    /// the type-driven rewrites (raw register/operand names are emitted).
    pub addr: Option<Address>,
    /// When set, a binding-rewritten operand carries its underlying storage
    /// inline: `al` → `id@al`, `[si+3]` → `troop@si->occupation`. Only operands
    /// that were actually rewritten gain the suffix; raw labels are untouched.
    pub annotate_storage: bool,
}

impl ProjectLookup<'_> {
    /// If a base/index register at the current address carries a `*T` binding,
    /// render the dereference as `name->field` (or `name[i]` for arrays).
    fn typed_indirect(
        &self,
        base: Option<crate::BaseReg>,
        index: Option<crate::IndexReg>,
        disp: u16,
    ) -> Option<String> {
        let (seg_idx, ofs) = self.addr?;
        let locs = [
            index.map(|i| match i {
                crate::IndexReg::SI => crate::binding::Location::Gp16(crate::GpReg16::SI),
                crate::IndexReg::DI => crate::binding::Location::Gp16(crate::GpReg16::DI),
            }),
            base.map(|b| match b {
                crate::BaseReg::BX => crate::binding::Location::Gp16(crate::GpReg16::BX),
                crate::BaseReg::BP => crate::binding::Location::Gp16(crate::GpReg16::BP),
            }),
        ];
        for loc in locs.into_iter().flatten() {
            let Some(crate::type_prop::TypedVal::Typed { name, ty }) = self
                .project
                .type_prop
                .type_at(self.project, seg_idx, ofs, loc)
            else {
                continue;
            };
            let Some(pointee) = ty.as_ptr() else {
                continue;
            };
            // A named binding renders as `troop` (and `troop@si` when storage
            // annotation is on); an unnamed one falls back to the raw register
            // spelling, where a `@si` suffix would be redundant.
            let base_name = match name {
                Some(n) if self.annotate_storage => format!("{n}@{}", loc_default_name(loc)),
                Some(n) => n,
                None => loc_default_name(loc),
            };
            let path = self.project.field_path_in(pointee, disp as u32)?;
            return Some(if path.starts_with('[') {
                format!("{base_name}{path}")
            } else {
                format!("{base_name}->{path}")
            });
        }
        None
    }
}

impl SymbolLookup for ProjectLookup<'_> {
    fn lookup_direct(&self, seg: u16, ofs: u16, _width: crate::DataWidth) -> Option<String> {
        let idx = self.project.segment_index_for(seg)?;
        self.project.resolve_label(idx, ofs as u32)
    }

    fn lookup_register(&self, reg: crate::NamedReg) -> Option<String> {
        use crate::binding::Location;
        use crate::type_prop::{TypedVal, gp8_is_high, gp16_parent};
        let (seg_idx, ofs) = self.addr?;
        let tp = &self.project.type_prop;
        let name = match reg {
            crate::NamedReg::Gp16(r) => {
                match tp.type_at(self.project, seg_idx, ofs, Location::Gp16(r)) {
                    Some(TypedVal::Typed {
                        name: Some(name), ..
                    }) => Some(name),
                    _ => None,
                }
            }
            crate::NamedReg::Seg(r) => {
                match tp.type_at(self.project, seg_idx, ofs, Location::Seg(r)) {
                    Some(TypedVal::Typed {
                        name: Some(name), ..
                    }) => Some(name),
                    _ => None,
                }
            }
            crate::NamedReg::Gp8(r) => {
                // A direct 8-bit binding wins; otherwise a 16-bit parent binding
                // renders as `name.lo` / `name.hi`.
                if let Some(TypedVal::Typed {
                    name: Some(name), ..
                }) = tp.type_at(self.project, seg_idx, ofs, Location::Gp8(r))
                {
                    Some(name)
                } else if let Some(TypedVal::Typed {
                    name: Some(name), ..
                }) =
                    tp.type_at(self.project, seg_idx, ofs, Location::Gp16(gp16_parent(r)))
                {
                    let half = if gp8_is_high(r) { "hi" } else { "lo" };
                    Some(format!("{name}.{half}"))
                } else {
                    None
                }
            }
        };
        // The storage suffix names the register actually written (`@al`, `@ax`,
        // `@ds`) — `reg` itself, so an 8-bit access of a 16-bit binding reads
        // `id.lo@al`.
        name.map(|n| {
            if self.annotate_storage {
                format!("{n}@{reg}")
            } else {
                n
            }
        })
    }

    fn lookup_indirect(
        &self,
        seg: crate::SReg,
        base: Option<crate::BaseReg>,
        index: Option<crate::IndexReg>,
        disp: u16,
        _width: crate::DataWidth,
    ) -> Option<String> {
        // A `*T` binding on a base/index register rewrites `[si+3]` →
        // `troop->occupation`. This is segment-independent (near pointer, offset
        // only), so it runs before the segment-register resolution below and
        // only for static rendering (no live register file).
        if self.register_file.is_none()
            && let Some(name) = self.typed_indirect(base, index, disp)
        {
            return Some(name);
        }

        let seg = self.sreg_map.get(seg)?;
        let mut base = base;
        let mut index = index;
        let mut disp = disp;

        if let Some(rf) = self.register_file.as_ref() {
            if let Some(base_val) = base.map(|b| rf.get_base_reg(b)) {
                disp = disp.wrapping_add(base_val);
                base = None;
            }
            if let Some(index_val) = index.map(|b| rf.get_index_reg(b)) {
                disp = disp.wrapping_add(index_val);
                index = None;
            }
            // println!("\tseg={seg:?} base={base:?} index={index:?} disp={disp:#04x} w={_width:?}\n");
        }

        match (base, index) {
            // No register: a plain direct reference; keep its label unconditionally.
            (None, None) => self.project.resolve_label(seg, disp as u32),
            // A register is present, so this is an indexed access. Emit
            // `name[reg]` only when `disp` is covered by an array (so a scalar
            // global does not masquerade as one — see `is_register_indexable`).
            // The `*T` binding rewrite was already handled at the top.
            (base, index) => {
                if !self.project.is_register_indexable(seg, disp as u32) {
                    return None;
                }
                let name = self.project.resolve_label(seg, disp as u32)?;
                Some(match (base, index) {
                    (Some(base), None) => format!("{name}[{base}]"),
                    (None, Some(index)) => format!("{name}[{index}]"),
                    (Some(base), Some(index)) => format!("{name}[{base}+{index}]"),
                    (None, None) => unreachable!(),
                })
            }
        }
    }

    fn lookup_offset(&self, ofs: u16) -> Option<String> {
        self.project.resolve_label(self.default_seg?, ofs as u32)
    }

    fn lookup_segment(&self, seg_idx: SegmentIdx) -> Option<String> {
        Some(self.project.segments[seg_idx].name.to_string())
    }
}

// ── Segment auto-detection from EXE ──────────────────────────────────────────

fn make_segments(exe: &ExeMz) -> Segments {
    use std::collections::BTreeSet;

    let mut seg_set: BTreeSet<u16> = BTreeSet::new();
    seg_set.insert(exe.head.cs);
    seg_set.insert(exe.head.ss);

    for reloc in &exe.relocations {
        let ea = reloc.seg as usize * 16 + reloc.ofs as usize;
        if let Some(bytes) = exe.image.get(ea..ea + 2) {
            let seg = u16::from_le_bytes([bytes[0], bytes[1]]);
            seg_set.insert(seg);
        }
    }

    let segs: Vec<u16> = seg_set.into_iter().collect();
    let image_size = exe.image.len() as u32;

    segs.iter()
        .enumerate()
        .map(|(i, &seg)| {
            let start = seg as u32 * 16;
            let end = segs.get(i + 1).map_or(image_size, |&s| s as u32 * 16);
            println!("seg: start={start:x}, end={end:x}");
            Segment {
                name: format!("seg{i:03}"),
                r#type: None,
                start: Some(0),
                end: Some(end - start),
                addr_attributes: AddressAttributes::new((end - start) as usize),
                assume: Assumes::default(),
                load: Some(LoadExpr {
                    file_idx: 0,
                    seg_start: 0,
                    seg_end: None,
                    file_start: start,
                    file_end: if end == image_size { None } else { Some(end) },
                }),
            }
        })
        .collect::<Vec<_>>()
        .into()
}

// ── Ofs16 target collection ───────────────────────────────────────────────────

fn sha1_of(data: &[u8]) -> Vec<u8> {
    Sha1::digest(data).to_vec()
}

fn collect_ofs16_targets(
    data_type: &DataType,
    bytes: &[u8],
    structs: &Structs,
    fallback_seg: Option<SegmentIdx>,
    targets: &mut Vec<Address>,
) {
    match data_type {
        DataType::Scalar(scalar) => {
            let seg = match scalar {
                ScalarDataType::Ofs16(seg_opt) => seg_opt.or(fallback_seg),
                ScalarDataType::U16 => fallback_seg,
                _ => None,
            };
            if let Some(seg_idx) = seg {
                let lo = bytes.first().copied().unwrap_or(0) as u32;
                let hi = bytes.get(1).copied().unwrap_or(0) as u32;
                targets.push((seg_idx, lo | (hi << 8)));
            }
        }
        DataType::Composite(CompositeDataType::Struct(idx)) => {
            let mut cursor = 0usize;
            for f in &structs[*idx].fields {
                let field_bytes = bytes.get(cursor..).unwrap_or(&[]);
                collect_ofs16_targets(&f.r#type, field_bytes, structs, None, targets);
                cursor += f.r#type.byte_size(field_bytes, structs);
            }
        }
        DataType::Composite(CompositeDataType::Array { elem, count }) => {
            let mut cursor = 0usize;
            for _ in 0..*count {
                let elem_bytes = bytes.get(cursor..).unwrap_or(&[]);
                collect_ofs16_targets(elem, elem_bytes, structs, None, targets);
                cursor += elem.byte_size(elem_bytes, structs);
            }
        }
        DataType::Formatted(_, inner) => {
            collect_ofs16_targets(inner, bytes, structs, fallback_seg, targets);
        }
        // Pointers and tuples are binding-only types; they carry no data-table
        // ofs16 targets.
        DataType::Ptr(_) | DataType::Tuple(_) => {}
    }
}

#[cfg(test)]
mod field_path_tests {
    use super::*;

    #[test]
    fn resolves_struct_field_offsets() {
        // Troop: occupation at +3, armyskill at +0x17 (matching the design note).
        let chani = "project[t]:\n\
                     arch = 8086\n\
                     segment[seg000]: type = code; start = 0; end = 0x100\n\
                     struct[Troop]: _pad0 = [u8; 3]; occupation = u8; _pad1 = [u8; 19]; armyskill = u8\n\
                     end\n";
        let p = Project::from_str(chani).unwrap();
        let troop = DataType::Composite(CompositeDataType::Struct(0));

        assert_eq!(p.field_path_in(&troop, 3).as_deref(), Some("occupation"));
        assert_eq!(p.field_path_in(&troop, 0x17).as_deref(), Some("armyskill"));
        // Offset 0 lands on the start of the leading field (no index suffix).
        assert_eq!(p.field_path_in(&troop, 0).as_deref(), Some("_pad0"));
        // Out of range.
        assert_eq!(p.field_path_in(&troop, 0x100), None);

        // A pointer to an array resolves to an index accessor.
        let arr = DataType::Composite(CompositeDataType::Array {
            elem: Box::new(DataType::Scalar(ScalarDataType::U16)),
            count: 4,
        });
        assert_eq!(p.field_path_in(&arr, 4).as_deref(), Some("[2]"));
    }
}

#[cfg(test)]
mod mutator_tests {
    use super::*;

    fn project() -> Project {
        let chani = "project[t]:\n\
                     arch = 8086\n\
                     segment[seg000]: type = code; start = 0; end = 0x100\n\
                     end\n";
        Project::from_str(chani).unwrap()
    }

    #[test]
    fn add_rename_and_field_round_trip() {
        let mut p = project();
        let idx = p.add_struct("Troop").unwrap();
        assert!(p.add_struct("Troop").is_err(), "duplicate name rejected");
        assert!(p.add_struct("  ").is_err(), "empty name rejected");

        p.set_struct_field(
            idx,
            None,
            "occupation",
            DataType::Scalar(ScalarDataType::U8),
        )
        .unwrap();
        p.set_struct_field(idx, None, "skill", DataType::Scalar(ScalarDataType::U16))
            .unwrap();
        assert!(
            p.set_struct_field(
                idx,
                None,
                "occupation",
                DataType::Scalar(ScalarDataType::U8)
            )
            .is_err(),
            "duplicate field name rejected"
        );
        p.rename_struct(idx, "Soldier").unwrap();

        // Serialize and re-parse: the struct survives a round trip.
        let mut buf = Vec::new();
        p.write_to(&mut buf).unwrap();
        let p2 = Project::from_str(std::str::from_utf8(&buf).unwrap()).unwrap();
        let def = p2.structs.iter().find(|s| s.name == "Soldier").unwrap();
        assert_eq!(def.fields.len(), 2);
        assert_eq!(def.fields[0].name, "occupation");
    }

    #[test]
    fn struct_and_field_comments_round_trip() {
        let mut p = project();
        let idx = p.add_struct("ModCarOffset").unwrap();
        p.set_struct_field(idx, None, "mod_off", DataType::Scalar(ScalarDataType::U8))
            .unwrap();
        p.set_struct_field(idx, None, "car_off", DataType::Scalar(ScalarDataType::U8))
            .unwrap();
        p.set_struct_comment(idx, Some("Per-channel OPL operator offsets.".to_string()));
        // A comment containing ';' and a newline exercises the `[[[ ]]]` encoding
        // inside the inline `field[...]` dict.
        p.set_struct_field_comment(
            idx,
            0,
            Some("modulator base; line one\nline two".to_string()),
        );

        // Editing a field's name/type preserves its comment.
        p.set_struct_field(
            idx,
            Some(0),
            "mod_off",
            DataType::Scalar(ScalarDataType::U8),
        )
        .unwrap();
        assert_eq!(
            p.structs[idx].fields[0].comment.as_deref(),
            Some("modulator base; line one\nline two")
        );

        let mut buf = Vec::new();
        p.write_to(&mut buf).unwrap();
        let text = std::str::from_utf8(&buf).unwrap();
        assert!(
            text.contains("field[mod_off]:"),
            "expected nested field form:\n{text}"
        );

        let p2 = Project::from_str(text).unwrap();
        let def = p2
            .structs
            .iter()
            .find(|s| s.name == "ModCarOffset")
            .unwrap();
        assert_eq!(
            def.comment.as_deref(),
            Some("Per-channel OPL operator offsets.")
        );
        assert_eq!(
            def.fields[0].comment.as_deref(),
            Some("modulator base; line one\nline two")
        );
        assert_eq!(def.fields[1].comment, None);
    }

    #[test]
    fn legacy_flat_struct_parses_and_upgrades() {
        // The old flat `field = type` form, plus a struct-level `comment`, still
        // loads; re-serialization emits the nested `field[...]` form.
        let chani = "project[t]:\n\
                     arch = 8086\n\
                     segment[seg000]: type = code; start = 0; end = 0x100\n\
                     struct[Troop]:\n\
                         comment = a troop record\n\
                         occupation = u8\n\
                         skill = u16\n\
                     end\n\
                     end\n";
        let p = Project::from_str(chani).unwrap();
        let def = &p.structs[0];
        assert_eq!(def.name, "Troop");
        assert_eq!(def.comment.as_deref(), Some("a troop record"));
        assert_eq!(def.fields.len(), 2);
        assert_eq!(def.fields[0].name, "occupation");
        assert_eq!(def.fields[0].comment, None);

        let mut buf = Vec::new();
        p.write_to(&mut buf).unwrap();
        let text = std::str::from_utf8(&buf).unwrap();
        assert!(
            text.contains("field[occupation]: type = u8"),
            "expected upgraded nested form:\n{text}"
        );
    }

    #[test]
    fn remove_struct_is_guarded_and_reindexes() {
        let mut p = project();
        let a = p.add_struct("A").unwrap();
        let b = p.add_struct("B").unwrap();
        let addr = (p.segment_by_name("seg000").unwrap(), 0x10);

        // Point an attr at B, then removing A must re-point B's reference.
        let bt = p.parse_type_str("B").unwrap();
        p.set_attr_type(addr, Some(bt));
        // A is unreferenced — removal succeeds and shifts B from index 1 to 0.
        assert_eq!((a, b), (0, 1));
        p.remove_struct(a).unwrap();
        assert_eq!(
            p.attrs[&addr]
                .r#type
                .as_ref()
                .unwrap()
                .type_str(&p.segments, &p.structs),
            "B"
        );

        // Now B is referenced — removal is refused.
        assert!(p.remove_struct(0).is_err());
    }

    #[test]
    fn field_cycle_rejected_pointer_allowed() {
        let mut p = project();
        let a = p.add_struct("A").unwrap();
        let b = p.add_struct("B").unwrap();
        p.set_struct_field(a, None, "b", p.parse_data_type("B").unwrap())
            .unwrap();
        assert!(
            p.set_struct_field(b, None, "a", p.parse_data_type("A").unwrap())
                .is_err(),
            "by-value cycle rejected"
        );
        assert!(
            p.set_struct_field(b, None, "a", p.parse_data_type("*A").unwrap())
                .is_ok(),
            "pointer breaks the cycle"
        );
    }

    #[test]
    fn attr_type_let_signature_setters_drop_empty() {
        let mut p = project();
        let addr = (p.segment_by_name("seg000").unwrap(), 0x20);

        p.set_attr_type(addr, Some(AttrType::Code));
        assert!(p.attrs.contains_key(&addr));
        p.set_attr_type(addr, None);
        assert!(
            !p.attrs.contains_key(&addr),
            "clearing the only field drops the attr"
        );

        let lets = crate::binding::parse_binding_list("tmp: u16 @ -2", &p.segments, &[]).unwrap();
        p.set_attr_lets(addr, lets);
        assert_eq!(p.attrs[&addr].lets.len(), 1);
        p.set_attr_lets(addr, Vec::new());
        assert!(!p.attrs.contains_key(&addr));

        let sig = crate::binding::parse_binding_list("in p: u8 @al", &p.segments, &[]).unwrap();
        p.set_attr_signature(addr, Some(sig));
        assert!(p.attrs[&addr].signature.is_some());
        p.set_attr_signature(addr, Some(Vec::new()));
        assert!(!p.attrs.contains_key(&addr), "an empty signature clears");
    }
}
